import { NextRequest, NextResponse } from 'next/server';
import { authForAI, runAI } from '@/lib/aiHelpers';
import { prisma } from '@/lib/prisma';

const DEFAULT_SETUP_PLAN = {
  summary: 'Create a practical CRM setup pack for lead routing, deal quality, dashboard visibility, and custom qualification data.',
  workflows: [
    {
      name: 'AI Setup - High Score Lead Routing',
      description: 'Route qualified leads to account managers when score reaches 80 or higher.',
      objectType: 'Lead',
      triggerType: 'ON_CREATE_OR_UPDATE',
      conditions: { all: [{ field: 'qualificationScore', operator: 'gte', value: 80 }] },
      actions: [{ type: 'CREATE_TASK', subject: 'Contact high-score lead within 24 hours', priority: 'HIGH' }],
    },
  ],
  validationRules: [
    {
      name: 'AI_Setup_Opportunity_Close_Date_Required',
      objectType: 'Opportunity',
      formula: 'AND(ISPICKVAL(stage, "PROPOSAL"), ISBLANK(expectedCloseDate))',
      errorMessage: 'Expected close date is required before moving an opportunity to Proposal.',
    },
  ],
  dashboards: [
    {
      name: 'AI Setup - Revenue Command Center',
      layout: { columns: 12, rowHeight: 96 },
      widgets: [
        { id: 'pipeline-by-stage', type: 'bar', title: 'Pipeline by Stage', source: 'opportunities' },
        { id: 'lead-quality', type: 'scorecard', title: 'Lead Quality', source: 'leads' },
        { id: 'ai-errors', type: 'table', title: 'AI Exceptions', source: 'ai_results' },
      ],
    },
  ],
  customObjects: [
    {
      name: 'Qualification_Playbook__c',
      label: 'Qualification Playbook',
      pluralLabel: 'Qualification Playbooks',
      description: 'Stores reusable qualification criteria generated by Setup AI.',
      fields: [
        { name: 'Segment__c', label: 'Segment', type: 'TEXT', isRequired: true, maxLength: 120 },
        { name: 'Score_Threshold__c', label: 'Score Threshold', type: 'NUMBER', defaultValue: '75' },
        { name: 'Next_Action__c', label: 'Next Action', type: 'TEXT', maxLength: 255 },
      ],
    },
  ],
};

export async function GET() {
  const auth = await authForAI();
  if (auth instanceof Response) return auth;

  const [workflows, validationRules, dashboards, customObjects] = await Promise.all([
    prisma.workflowRule.findMany({ orderBy: { createdAt: 'desc' }, take: 5 }),
    prisma.validationRule.findMany({ orderBy: { createdAt: 'desc' }, take: 5 }),
    prisma.dynamicDashboard.findMany({ orderBy: { createdAt: 'desc' }, take: 5 }),
    prisma.customObject.findMany({ orderBy: { createdAt: 'desc' }, take: 5, include: { fields: true } }),
  ]);

  return NextResponse.json({ workflows, validationRules, dashboards, customObjects });
}

export async function POST(req: NextRequest) {
  const auth = await authForAI();
  if (auth instanceof Response) return auth;

  try {
    const { objective, apply = false } = await req.json().catch(() => ({}));
    const prompt = `Generate a Salesforce-style CRM setup implementation plan for this request:

${objective || DEFAULT_SETUP_PLAN.summary}

Return ONLY JSON with this shape:
{
  "summary": "short implementation summary",
  "workflows": [{"name":"","description":"","objectType":"Lead|Opportunity|Case|Task","triggerType":"","conditions":{},"actions":[]}],
  "validationRules": [{"name":"","objectType":"","formula":"","errorMessage":""}],
  "dashboards": [{"name":"","layout":{},"widgets":[]}],
  "customObjects": [{"name":"Something__c","label":"","pluralLabel":"","description":"","fields":[{"name":"Field__c","label":"","type":"TEXT|NUMBER|DATE|BOOLEAN|PICKLIST","isRequired":false,"defaultValue":"","picklistValues":[]}]}]
}`;

    let plan: any;
    try {
      plan = await runAI(auth, prompt, {
        feature: 'setup-ai',
        systemPrompt: 'You are a Salesforce setup architect. Return valid JSON only. Keep generated configuration safe, minimal, and directly applicable.',
        json: true,
        temperature: 0.2,
        maxTokens: 1800,
        inputPayload: { objective, apply },
      });
    } catch {
      plan = DEFAULT_SETUP_PLAN;
    }

    const normalized = normalizePlan(plan);
    const created = apply ? await applyPlan(normalized, auth.userId) : null;

    return NextResponse.json({ plan: normalized, applied: Boolean(apply), created });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Failed to run Setup AI' }, { status: 500 });
  }
}

function normalizePlan(plan: any) {
  return {
    summary: String(plan?.summary || DEFAULT_SETUP_PLAN.summary),
    workflows: Array.isArray(plan?.workflows) ? plan.workflows.slice(0, 3) : DEFAULT_SETUP_PLAN.workflows,
    validationRules: Array.isArray(plan?.validationRules) ? plan.validationRules.slice(0, 3) : DEFAULT_SETUP_PLAN.validationRules,
    dashboards: Array.isArray(plan?.dashboards) ? plan.dashboards.slice(0, 2) : DEFAULT_SETUP_PLAN.dashboards,
    customObjects: Array.isArray(plan?.customObjects) ? plan.customObjects.slice(0, 2) : DEFAULT_SETUP_PLAN.customObjects,
  };
}

async function applyPlan(plan: any, userId: string) {
  const workflows = await Promise.all(
    plan.workflows.map((workflow: any) =>
      prisma.workflowRule.create({
        data: {
          name: String(workflow.name || 'AI Setup Workflow').slice(0, 180),
          description: workflow.description ? String(workflow.description) : null,
          objectType: String(workflow.objectType || 'Lead'),
          triggerType: String(workflow.triggerType || 'ON_CREATE_OR_UPDATE'),
          conditions: workflow.conditions || {},
          actions: Array.isArray(workflow.actions) ? workflow.actions : [],
          isActive: true,
          priority: 10,
        },
      })
    )
  );

  const validationRules = await Promise.all(
    plan.validationRules.map((rule: any) =>
      prisma.validationRule.create({
        data: {
          name: sanitizeApiName(rule.name || 'AI_Setup_Validation_Rule'),
          objectType: String(rule.objectType || 'Lead'),
          formula: String(rule.formula || 'FALSE'),
          errorMessage: String(rule.errorMessage || 'This record does not meet the configured validation rule.'),
          isActive: true,
        },
      })
    )
  );

  const dashboards = await Promise.all(
    plan.dashboards.map((dashboard: any) =>
      prisma.dynamicDashboard.create({
        data: {
          name: String(dashboard.name || 'AI Setup Dashboard').slice(0, 180),
          layout: dashboard.layout || { columns: 12 },
          widgets: Array.isArray(dashboard.widgets) ? dashboard.widgets : [],
          ownerId: userId,
          isDefault: false,
        },
      })
    )
  );

  const customObjects = [];
  for (const customObject of plan.customObjects) {
    const objectName = ensureCustomObjectName(customObject.name || customObject.label || 'AI_Setup_Object');
    const createdObject = await prisma.customObject.create({
      data: {
        name: objectName,
        label: String(customObject.label || objectName.replace('__c', '').replace(/_/g, ' ')).slice(0, 120),
        pluralLabel: String(customObject.pluralLabel || `${customObject.label || 'AI Setup Object'}s`).slice(0, 140),
        description: customObject.description ? String(customObject.description) : null,
        fields: {
          create: (Array.isArray(customObject.fields) ? customObject.fields : []).slice(0, 8).map((field: any, index: number) => ({
            name: ensureCustomFieldName(field.name || field.label || `Field_${index + 1}`),
            label: String(field.label || field.name || `Field ${index + 1}`).replace('__c', '').slice(0, 120),
            type: String(field.type || 'TEXT').toUpperCase(),
            isRequired: Boolean(field.isRequired),
            defaultValue: field.defaultValue ? String(field.defaultValue) : null,
            picklistValues: Array.isArray(field.picklistValues) ? field.picklistValues.map(String) : [],
            sortOrder: index,
          })),
        },
      },
      include: { fields: true },
    });
    customObjects.push(createdObject);
  }

  return { workflows, validationRules, dashboards, customObjects };
}

function sanitizeApiName(value: string) {
  return value.replace(/[^A-Za-z0-9_]/g, '_').replace(/^([^A-Za-z])/, 'Rule_$1').slice(0, 120);
}

function ensureCustomObjectName(value: string) {
  const base = sanitizeApiName(value.replace(/__c$/, '')).replace(/_+$/g, '') || 'AI_Setup_Object';
  return `${base}_${Date.now().toString().slice(-5)}__c`;
}

function ensureCustomFieldName(value: string) {
  const base = sanitizeApiName(value.replace(/__c$/, '')).replace(/_+$/g, '') || 'Field';
  return `${base}__c`;
}
