import { NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

export async function GET() {
  try {
    console.log('🌱 Creating leads for 6 new business sectors...');

    // Get the new client companies
    const newClients = await prisma.clientCompany.findMany({
      where: {
        businessSector: {
          in: ['HOSPITALITY', 'FITNESS_WELLNESS', 'CONSTRUCTION', 'ECOMMERCE', 'INSURANCE', 'SOLAR_ENERGY']
        }
      },
      include: {
        users: true
      }
    });

    if (newClients.length === 0) {
      return NextResponse.json({ error: 'No new sector clients found' }, { status: 404 });
    }

    let totalLeadsCreated = 0;
    let totalActivitiesCreated = 0;

    for (const client of newClients) {
      console.log(`Creating leads for ${client.name} (${client.businessSector})`);

      // Create a campaign for this client
      const admin = await prisma.user.findFirst({ where: { role: 'ADMIN' } });

      const campaign = await prisma.campaign.create({
        data: {
          clientId: client.id,
          name: `${client.name} - Lead Generation Campaign`,
          description: `Lead generation campaign for ${client.industry}`,
          status: 'ACTIVE',
          channel: 'MULTI_CHANNEL',
          targetPersona: getTargetPersona(client.businessSector),
          ownerId: admin?.id || client.users[0]?.id,
          startDate: new Date(),
        },
      });

      // Generate 15 leads for this sector
      const leads = generateLeadsForNewSector(client.businessSector);

      for (const leadData of leads) {
        const lead = await prisma.lead.create({
          data: {
            campaignId: campaign.id,
            clientId: client.id,
            fullName: leadData.fullName,
            company: leadData.company,
            title: leadData.title,
            email: leadData.email,
            phone: leadData.phone,
            leadSource: 'AGENCY',
            status: leadData.status,
            qualificationScore: leadData.score,
            customFields: leadData.customFields,
          },
        });

        totalLeadsCreated++;

        // Create 5-10 activities for each lead
        const activityCount = Math.floor(Math.random() * 6) + 5;
        const activities = generateActivities(lead.fullName, activityCount);

        for (const activityData of activities) {
          await prisma.leadActivity.create({
            data: {
              leadId: lead.id,
              userId: client.users[0]?.id,
              type: activityData.type as any,
              content: activityData.content,
              aiSummary: activityData.aiSummary,
              createdAt: activityData.createdAt,
            },
          });
          totalActivitiesCreated++;
        }
      }
    }

    console.log(`✅ Created ${totalLeadsCreated} leads and ${totalActivitiesCreated} activities`);

    return NextResponse.json({
      message: 'Successfully created leads for new sectors',
      leadsCreated: totalLeadsCreated,
      activitiesCreated: totalActivitiesCreated,
    });

  } catch (error) {
    console.error('Seed error:', error);
    return NextResponse.json({ error: 'Seeding failed', details: String(error) }, { status: 500 });
  }
}

function getTargetPersona(sector: string): string {
  const personas: Record<string, string> = {
    HOSPITALITY: 'Hotel owners, restaurant managers, event venue operators',
    FITNESS_WELLNESS: 'Gym owners, yoga studio operators, wellness center managers',
    CONSTRUCTION: 'Homeowners seeking renovations, commercial property developers',
    ECOMMERCE: 'Online store owners, marketplace sellers, DTC brand owners',
    INSURANCE: 'Individuals and families seeking life, health, auto insurance',
    SOLAR_ENERGY: 'Homeowners and businesses interested in solar installation',
  };
  return personas[sector] || 'General prospects';
}

function generateLeadsForNewSector(sector: string) {
  const statuses = ['NEW', 'CONTACTED', 'QUALIFIED', 'UNQUALIFIED'];

  const sectorLeads: Record<string, any[]> = {
    HOSPITALITY: [
      {
        fullName: 'Maria Santos',
        company: 'Seaside Restaurant',
        title: 'Owner',
        email: 'maria.s@seasiderestaurant.com',
        phone: '555-3101',
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          businessType: 'Restaurant',
          serviceNeeded: 'POS System',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Soon (1-3 months)',
        },
      },
      {
        fullName: 'James Park',
        company: 'Downtown Event Hall',
        title: 'Manager',
        email: 'james.p@downtownevents.com',
        phone: '555-3102',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          businessType: 'Event Venue',
          serviceNeeded: 'Event Management',
          currentCapacity: 'Large (100-500 seats/rooms)',
          budget: '$20K - $50K',
          timeline: 'Urgent (this month)',
        },
      },
      {
        fullName: 'Sofia Lopez',
        company: 'Boutique Hotel Miramar',
        title: 'General Manager',
        email: 'sofia.l@hotelmiramar.com',
        phone: '555-3103',
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          businessType: 'Hotel/Motel',
          serviceNeeded: 'Booking/Reservation Software',
          currentCapacity: 'Small (1-20 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Robert Kim',
        company: 'Elite Catering Services',
        title: 'CEO',
        email: 'robert.k@elitecatering.com',
        phone: '555-3104',
        status: 'NEW',
        score: 78,
        customFields: {
          businessType: 'Catering',
          serviceNeeded: 'Marketing Services',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Planning (3+ months)',
        },
      },
      {
        fullName: 'Emily Watson',
        company: 'Sunset Bar & Grill',
        title: 'Co-Owner',
        email: 'emily.w@sunsetbar.com',
        phone: '555-3105',
        status: 'CONTACTED',
        score: 82,
        customFields: {
          businessType: 'Bar/Nightclub',
          serviceNeeded: 'POS System',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Soon (1-3 months)',
        },
      },
      {
        fullName: 'Michael Torres',
        company: 'Garden Inn B&B',
        title: 'Owner',
        email: 'michael.t@gardeninn.com',
        phone: '555-3106',
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          businessType: 'Bed & Breakfast',
          serviceNeeded: 'Booking/Reservation Software',
          currentCapacity: 'Small (1-20 seats/rooms)',
          budget: 'Under $5K',
          timeline: 'Soon (1-3 months)',
        },
      },
      {
        fullName: 'Lisa Chang',
        company: 'Fusion Bistro',
        title: 'Manager',
        email: 'lisa.c@fusionbistro.com',
        phone: '555-3107',
        status: 'NEW',
        score: 75,
        customFields: {
          businessType: 'Restaurant',
          serviceNeeded: 'Staff Training',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: 'Under $5K',
          timeline: 'Planning (3+ months)',
        },
      },
      {
        fullName: 'David Chen',
        company: 'Metropolitan Conference Center',
        title: 'Director',
        email: 'david.c@metroconf.com',
        phone: '555-3108',
        status: 'CONTACTED',
        score: 91,
        customFields: {
          businessType: 'Event Venue',
          serviceNeeded: 'Event Management',
          currentCapacity: 'Enterprise (500+ seats/rooms)',
          budget: 'Over $100K',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Anna Rodriguez',
        company: 'Cozy Corner Cafe',
        title: 'Owner',
        email: 'anna.r@cozycafe.com',
        phone: '555-3109',
        status: 'NEW',
        score: 70,
        customFields: {
          businessType: 'Restaurant',
          serviceNeeded: 'POS System',
          currentCapacity: 'Small (1-20 seats/rooms)',
          budget: 'Under $5K',
          timeline: 'Planning (3+ months)',
        },
      },
      {
        fullName: 'Thomas Wilson',
        company: 'Luxury Catering Group',
        title: 'Operations Manager',
        email: 'thomas.w@luxurycatering.com',
        phone: '555-3110',
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          businessType: 'Catering',
          serviceNeeded: 'Consulting',
          currentCapacity: 'Large (100-500 seats/rooms)',
          budget: '$20K - $50K',
          timeline: 'Soon (1-3 months)',
        },
      },
      {
        fullName: 'Jennifer Lee',
        company: 'Riverfront Hotel',
        title: 'Assistant Manager',
        email: 'jennifer.l@riverfronthotel.com',
        phone: '555-3111',
        status: 'CONTACTED',
        score: 84,
        customFields: {
          businessType: 'Hotel/Motel',
          serviceNeeded: 'Marketing Services',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Urgent (this month)',
        },
      },
      {
        fullName: 'Carlos Martinez',
        company: 'Fiesta Event Venue',
        title: 'Owner',
        email: 'carlos.m@fiestavenue.com',
        phone: '555-3112',
        status: 'NEW',
        score: 72,
        customFields: {
          businessType: 'Event Venue',
          serviceNeeded: 'Event Management',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Planning (3+ months)',
        },
      },
      {
        fullName: 'Rachel Green',
        company: 'Skyline Lounge',
        title: 'Manager',
        email: 'rachel.g@skylinelounge.com',
        phone: '555-3113',
        status: 'QUALIFIED',
        score: 89,
        customFields: {
          businessType: 'Bar/Nightclub',
          serviceNeeded: 'Marketing Services',
          currentCapacity: 'Large (100-500 seats/rooms)',
          budget: '$20K - $50K',
          timeline: 'Soon (1-3 months)',
        },
      },
      {
        fullName: 'Daniel Brown',
        company: 'Gourmet Kitchen Catering',
        title: 'Head Chef & Owner',
        email: 'daniel.b@gourmetkitchen.com',
        phone: '555-3114',
        status: 'CONTACTED',
        score: 80,
        customFields: {
          businessType: 'Catering',
          serviceNeeded: 'POS System',
          currentCapacity: 'Medium (21-100 seats/rooms)',
          budget: '$5K - $20K',
          timeline: 'Urgent (this month)',
        },
      },
      {
        fullName: 'Susan Taylor',
        company: 'Harbor Inn',
        title: 'General Manager',
        email: 'susan.t@harborinn.com',
        phone: '555-3115',
        status: 'QUALIFIED',
        score: 93,
        customFields: {
          businessType: 'Bed & Breakfast',
          serviceNeeded: 'Booking/Reservation Software',
          currentCapacity: 'Small (1-20 seats/rooms)',
          budget: 'Under $5K',
          timeline: 'Immediate (this week)',
        },
      },
    ],

    FITNESS_WELLNESS: [
      {
        fullName: 'Alex Johnson',
        company: 'PowerFit Gym',
        title: 'Owner',
        email: 'alex.j@powerfitgym.com',
        phone: '555-4101',
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          businessType: 'Gym/Fitness Center',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Lead Generation',
          challenges: 'Getting new members',
          budget: '$1,500 - $5,000/mo',
        },
      },
      {
        fullName: 'Sophia Martinez',
        company: 'Harmony Yoga Studio',
        title: 'Founder',
        email: 'sophia.m@harmonyyoga.com',
        phone: '555-4102',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          businessType: 'Yoga Studio',
          membershipGoal: 'Startup (0-50 members)',
          serviceNeeded: 'Membership Management',
          challenges: 'Billing/payments',
          budget: 'Under $500/mo',
        },
      },
      {
        fullName: 'Mike Rodriguez',
        company: 'Elite CrossFit Box',
        title: 'Head Coach',
        email: 'mike.r@elitecrossfit.com',
        phone: '555-4103',
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          businessType: 'CrossFit Box',
          membershipGoal: 'Established (201-500 members)',
          serviceNeeded: 'Software/Technology',
          challenges: 'Scheduling/booking',
          budget: '$1,500 - $5,000/mo',
        },
      },
      {
        fullName: 'Emma Davis',
        company: 'Zen Pilates Studio',
        title: 'Owner',
        email: 'emma.d@zenpilates.com',
        phone: '555-4104',
        status: 'NEW',
        score: 78,
        customFields: {
          businessType: 'Pilates Studio',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Marketing Services',
          challenges: 'Getting new members',
          budget: '$500 - $1,500/mo',
        },
      },
      {
        fullName: 'Chris Anderson',
        company: 'Iron Warriors MMA',
        title: 'Owner',
        email: 'chris.a@ironwarriors.com',
        phone: '555-4105',
        status: 'CONTACTED',
        score: 82,
        customFields: {
          businessType: 'Martial Arts',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Lead Generation',
          challenges: 'Retention/churn',
          budget: '$500 - $1,500/mo',
        },
      },
      {
        fullName: 'Laura White',
        company: 'Serenity Spa & Wellness',
        title: 'Director',
        email: 'laura.w@serenityspa.com',
        phone: '555-4106',
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          businessType: 'Spa/Wellness Center',
          membershipGoal: 'Established (201-500 members)',
          serviceNeeded: 'Marketing Services',
          challenges: 'Getting new members',
          budget: 'Over $5,000/mo',
        },
      },
      {
        fullName: 'Kevin Brown',
        company: 'Athletic Performance Lab',
        title: 'Head Trainer',
        email: 'kevin.b@athleticlab.com',
        phone: '555-4107',
        status: 'NEW',
        score: 75,
        customFields: {
          businessType: 'Personal Training',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Software/Technology',
          challenges: 'Scheduling/booking',
          budget: '$500 - $1,500/mo',
        },
      },
      {
        fullName: 'Amanda Wilson',
        company: 'FlexFlow Yoga',
        title: 'Owner',
        email: 'amanda.w@flexflowyoga.com',
        phone: '555-4108',
        status: 'CONTACTED',
        score: 91,
        customFields: {
          businessType: 'Yoga Studio',
          membershipGoal: 'Large (500+ members)',
          serviceNeeded: 'Membership Management',
          challenges: 'Retention/churn',
          budget: '$1,500 - $5,000/mo',
        },
      },
      {
        fullName: 'Ryan Garcia',
        company: '24/7 Fitness Center',
        title: 'Manager',
        email: 'ryan.g@247fitness.com',
        phone: '555-4109',
        status: 'NEW',
        score: 70,
        customFields: {
          businessType: 'Gym/Fitness Center',
          membershipGoal: 'Large (500+ members)',
          serviceNeeded: 'Equipment Financing',
          challenges: 'Other',
          budget: 'Over $5,000/mo',
        },
      },
      {
        fullName: 'Nicole Lee',
        company: 'Core Strength Pilates',
        title: 'Instructor & Owner',
        email: 'nicole.l@corepilates.com',
        phone: '555-4110',
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          businessType: 'Pilates Studio',
          membershipGoal: 'Startup (0-50 members)',
          serviceNeeded: 'Lead Generation',
          challenges: 'Getting new members',
          budget: 'Under $500/mo',
        },
      },
      {
        fullName: 'Brandon Smith',
        company: 'Strike Force Martial Arts',
        title: 'Sensei',
        email: 'brandon.s@strikeforce.com',
        phone: '555-4111',
        status: 'CONTACTED',
        score: 84,
        customFields: {
          businessType: 'Martial Arts',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Marketing Services',
          challenges: 'Getting new members',
          budget: '$500 - $1,500/mo',
        },
      },
      {
        fullName: 'Jessica Chen',
        company: 'Vitality Wellness Center',
        title: 'Owner',
        email: 'jessica.c@vitalitywellness.com',
        phone: '555-4112',
        status: 'NEW',
        score: 72,
        customFields: {
          businessType: 'Spa/Wellness Center',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Consulting',
          challenges: 'Billing/payments',
          budget: '$1,500 - $5,000/mo',
        },
      },
      {
        fullName: 'Tyler Johnson',
        company: 'Beast Mode CrossFit',
        title: 'Owner',
        email: 'tyler.j@beastmode.com',
        phone: '555-4113',
        status: 'QUALIFIED',
        score: 89,
        customFields: {
          businessType: 'CrossFit Box',
          membershipGoal: 'Growing (51-200 members)',
          serviceNeeded: 'Lead Generation',
          challenges: 'Getting new members',
          budget: '$1,500 - $5,000/mo',
        },
      },
      {
        fullName: 'Megan Taylor',
        company: 'Personal Training Elite',
        title: 'Lead Trainer',
        email: 'megan.t@ptelite.com',
        phone: '555-4114',
        status: 'CONTACTED',
        score: 80,
        customFields: {
          businessType: 'Personal Training',
          membershipGoal: 'Startup (0-50 members)',
          serviceNeeded: 'Software/Technology',
          challenges: 'Scheduling/booking',
          budget: 'Under $500/mo',
        },
      },
      {
        fullName: 'Eric Martinez',
        company: 'Mega Gym 24',
        title: 'General Manager',
        email: 'eric.m@megagym24.com',
        phone: '555-4115',
        status: 'QUALIFIED',
        score: 93,
        customFields: {
          businessType: 'Gym/Fitness Center',
          membershipGoal: 'Large (500+ members)',
          serviceNeeded: 'Membership Management',
          challenges: 'Retention/churn',
          budget: 'Over $5,000/mo',
        },
      },
    ],

    CONSTRUCTION: [
      {
        fullName: 'Robert Thompson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'robert.t501@email.com',
        phone: '555-5101',
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          projectType: 'Addition',
          projectScope: 'Adding 500 sq ft master bedroom suite with bathroom',
          propertyType: 'Residential - Single Family',
          projectValue: '$50K - $250K',
          timeline: 'Soon (1-3 months)',
          permitsStatus: 'Need help with permits',
        },
      },
      {
        fullName: 'Jennifer Davis',
        company: 'Davis Properties LLC',
        title: 'Property Developer',
        email: 'jennifer.d502@email.com',
        phone: '555-5102',
        status: 'CONTACTED',
        score: 90,
        customFields: {
          projectType: 'New Construction',
          projectScope: '10,000 sq ft commercial office building, modern design',
          propertyType: 'Commercial - Office',
          projectValue: '$1M - $5M',
          timeline: 'Planning (3-6 months)',
          permitsStatus: 'Permits in hand',
        },
      },
      {
        fullName: 'Michael Johnson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'michael.j503@email.com',
        phone: '555-5103',
        status: 'NEW',
        score: 75,
        customFields: {
          projectType: 'Remodeling/Renovation',
          projectScope: 'Kitchen and bathroom full remodel, modern finishes',
          propertyType: 'Residential - Single Family',
          projectValue: '$50K - $250K',
          timeline: 'Planning (3-6 months)',
          permitsStatus: 'Not applicable',
        },
      },
      {
        fullName: 'Sarah Martinez',
        company: 'Retail Ventures Inc',
        title: 'VP Operations',
        email: 'sarah.m504@email.com',
        phone: '555-5104',
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          projectType: 'Commercial Build-out',
          projectScope: '5,000 sq ft retail space build-out in shopping center',
          propertyType: 'Commercial - Retail',
          projectValue: '$250K - $1M',
          timeline: 'Immediate - ready to start',
          permitsStatus: 'Permits pending',
        },
      },
      {
        fullName: 'David Lee',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'david.l505@email.com',
        phone: '555-5105',
        status: 'CONTACTED',
        score: 82,
        customFields: {
          projectType: 'Repair/Restoration',
          projectScope: 'Foundation repair and waterproofing basement',
          propertyType: 'Residential - Single Family',
          projectValue: 'Under $50K',
          timeline: 'Soon (1-3 months)',
          permitsStatus: 'Not applicable',
        },
      },
      {
        fullName: 'Lisa Anderson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'lisa.a506@email.com',
        phone: '555-5106',
        status: 'NEW',
        score: 70,
        customFields: {
          projectType: 'Addition',
          projectScope: 'Deck and outdoor living space, 300 sq ft',
          propertyType: 'Residential - Single Family',
          projectValue: 'Under $50K',
          timeline: 'Future (6+ months)',
          permitsStatus: 'Need help with permits',
        },
      },
      {
        fullName: 'James Wilson',
        company: 'Wilson Development Group',
        title: 'CEO',
        email: 'james.w507@email.com',
        phone: '555-5107',
        status: 'QUALIFIED',
        score: 93,
        customFields: {
          projectType: 'New Construction',
          projectScope: '20-unit multi-family residential complex',
          propertyType: 'Residential - Multi Family',
          projectValue: 'Over $5M',
          timeline: 'Planning (3-6 months)',
          permitsStatus: 'Permits in hand',
        },
      },
      {
        fullName: 'Emily Brown',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'emily.b508@email.com',
        phone: '555-5108',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          projectType: 'Remodeling/Renovation',
          projectScope: 'Whole house renovation, including electrical and plumbing',
          propertyType: 'Residential - Single Family',
          projectValue: '$250K - $1M',
          timeline: 'Soon (1-3 months)',
          permitsStatus: 'Permits pending',
        },
      },
      {
        fullName: 'Thomas Garcia',
        company: 'Manufacturing Solutions LLC',
        title: 'Facilities Manager',
        email: 'thomas.g509@email.com',
        phone: '555-5109',
        status: 'NEW',
        score: 72,
        customFields: {
          projectType: 'Commercial Build-out',
          projectScope: '15,000 sq ft warehouse expansion',
          propertyType: 'Industrial',
          projectValue: '$1M - $5M',
          timeline: 'Future (6+ months)',
          permitsStatus: 'Not applicable',
        },
      },
      {
        fullName: 'Amanda Taylor',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'amanda.t510@email.com',
        phone: '555-5110',
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          projectType: 'Addition',
          projectScope: 'Sunroom addition, 400 sq ft glass enclosed',
          propertyType: 'Residential - Single Family',
          projectValue: '$50K - $250K',
          timeline: 'Soon (1-3 months)',
          permitsStatus: 'Need help with permits',
        },
      },
      {
        fullName: 'Kevin Rodriguez',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'kevin.r511@email.com',
        phone: '555-5111',
        status: 'CONTACTED',
        score: 80,
        customFields: {
          projectType: 'Remodeling/Renovation',
          projectScope: 'Basement finishing, 800 sq ft living space',
          propertyType: 'Residential - Single Family',
          projectValue: '$50K - $250K',
          timeline: 'Immediate - ready to start',
          permitsStatus: 'Permits in hand',
        },
      },
      {
        fullName: 'Rachel White',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'rachel.w512@email.com',
        phone: '555-5112',
        status: 'NEW',
        score: 68,
        customFields: {
          projectType: 'Repair/Restoration',
          projectScope: 'Roof replacement and siding repair',
          propertyType: 'Residential - Single Family',
          projectValue: 'Under $50K',
          timeline: 'Future (6+ months)',
          permitsStatus: 'Not applicable',
        },
      },
      {
        fullName: 'Christopher Lee',
        company: 'Metro Retail Partners',
        title: 'Development Director',
        email: 'chris.l513@email.com',
        phone: '555-5113',
        status: 'QUALIFIED',
        score: 94,
        customFields: {
          projectType: 'Commercial Build-out',
          projectScope: 'Shopping center anchor tenant space, 25,000 sq ft',
          propertyType: 'Commercial - Retail',
          projectValue: 'Over $5M',
          timeline: 'Immediate - ready to start',
          permitsStatus: 'Permits in hand',
        },
      },
      {
        fullName: 'Michelle Chen',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'michelle.c514@email.com',
        phone: '555-5114',
        status: 'CONTACTED',
        score: 78,
        customFields: {
          projectType: 'Addition',
          projectScope: 'Two-car garage addition with storage loft',
          propertyType: 'Residential - Single Family',
          projectValue: '$50K - $250K',
          timeline: 'Planning (3-6 months)',
          permitsStatus: 'Need help with permits',
        },
      },
      {
        fullName: 'Daniel Martinez',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'daniel.m515@email.com',
        phone: '555-5115',
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          projectType: 'New Construction',
          projectScope: 'Custom home build, 3500 sq ft, modern farmhouse style',
          propertyType: 'Residential - Single Family',
          projectValue: '$250K - $1M',
          timeline: 'Soon (1-3 months)',
          permitsStatus: 'Permits pending',
        },
      },
    ],

    ECOMMERCE: [
      {
        fullName: 'Alex Thompson',
        company: 'TrendyShoesOnline',
        title: 'Founder',
        email: 'alex.t601@trendyshoes.com',
        phone: '555-6101',
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          businessStage: 'Growing (6 months - 2 years)',
          platform: 'Shopify',
          serviceNeeded: 'Marketing/Advertising',
          monthlyRevenue: '$25K - $100K',
          productCategory: 'Fashion - Footwear',
          budget: '$5K - $20K',
        },
      },
      {
        fullName: 'Jessica Parker',
        company: 'OrganicBeautyShop',
        title: 'Owner',
        email: 'jessica.p602@organicbeauty.com',
        phone: '555-6102',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          businessStage: 'New (0-6 months)',
          platform: 'WooCommerce',
          serviceNeeded: 'SEO/Traffic',
          monthlyRevenue: 'Under $5K',
          productCategory: 'Beauty & Cosmetics',
          budget: 'Under $1K',
        },
      },
      {
        fullName: 'Brandon Lee',
        company: 'TechGadgetsHub',
        title: 'CEO',
        email: 'brandon.l603@techgadgets.com',
        phone: '555-6103',
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          businessStage: 'Established (2+ years)',
          platform: 'Custom built',
          serviceNeeded: 'Fulfillment/Logistics',
          monthlyRevenue: '$100K - $500K',
          productCategory: 'Electronics',
          budget: '$20K - $50K',
        },
      },
      {
        fullName: 'Samantha Davis',
        company: 'ArtisanCraftsMarket',
        title: 'Founder',
        email: 'samantha.d604@artisancrafts.com',
        phone: '555-6104',
        status: 'NEW',
        score: 70,
        customFields: {
          businessStage: 'Pre-launch/Planning',
          platform: 'Etsy',
          serviceNeeded: 'Store setup/migration',
          monthlyRevenue: 'Not yet launched',
          productCategory: 'Handmade & Crafts',
          budget: 'Under $1K',
        },
      },
      {
        fullName: 'Marcus Johnson',
        company: 'FitGearPro',
        title: 'Owner',
        email: 'marcus.j605@fitgearpro.com',
        phone: '555-6105',
        status: 'CONTACTED',
        score: 88,
        customFields: {
          businessStage: 'Growing (6 months - 2 years)',
          platform: 'Shopify',
          serviceNeeded: 'Marketing/Advertising',
          monthlyRevenue: '$5K - $25K',
          productCategory: 'Sports & Fitness',
          budget: '$5K - $20K',
        },
      },
      {
        fullName: 'Emily Rodriguez',
        company: 'PetSuppliesPlus',
        title: 'Co-Founder',
        email: 'emily.r606@petsuppliesplus.com',
        phone: '555-6106',
        status: 'QUALIFIED',
        score: 86,
        customFields: {
          businessStage: 'Growing (6 months - 2 years)',
          platform: 'Amazon',
          serviceNeeded: 'Product sourcing',
          monthlyRevenue: '$5K - $25K',
          productCategory: 'Pet Supplies',
          budget: '$1K - $5K',
        },
      },
      {
        fullName: 'Ryan Chen',
        company: 'HomeDecorDirect',
        title: 'Managing Director',
        email: 'ryan.c607@homedecodirect.com',
        phone: '555-6107',
        status: 'NEW',
        score: 75,
        customFields: {
          businessStage: 'Established (2+ years)',
          platform: 'WooCommerce',
          serviceNeeded: 'SEO/Traffic',
          monthlyRevenue: '$25K - $100K',
          productCategory: 'Home Goods',
          budget: '$5K - $20K',
        },
      },
      {
        fullName: 'Nicole Martinez',
        company: 'BabyBoutiqueOnline',
        title: 'Owner',
        email: 'nicole.m608@babyboutique.com',
        phone: '555-6108',
        status: 'CONTACTED',
        score: 82,
        customFields: {
          businessStage: 'New (0-6 months)',
          platform: 'Shopify',
          serviceNeeded: 'Marketing/Advertising',
          monthlyRevenue: 'Under $5K',
          productCategory: 'Baby & Kids',
          budget: '$1K - $5K',
        },
      },
      {
        fullName: 'Kevin Wilson',
        company: 'OutdoorAdventureGear',
        title: 'CEO',
        email: 'kevin.w609@outdooradventure.com',
        phone: '555-6109',
        status: 'QUALIFIED',
        score: 93,
        customFields: {
          businessStage: 'Established (2+ years)',
          platform: 'Custom built',
          serviceNeeded: 'Consulting',
          monthlyRevenue: 'Over $500K',
          productCategory: 'Outdoor & Camping',
          budget: 'Over $50K',
        },
      },
      {
        fullName: 'Amanda Garcia',
        company: 'BookLoversMarket',
        title: 'Founder',
        email: 'amanda.g610@booklovers.com',
        phone: '555-6110',
        status: 'NEW',
        score: 72,
        customFields: {
          businessStage: 'Growing (6 months - 2 years)',
          platform: 'eBay',
          serviceNeeded: 'Store setup/migration',
          monthlyRevenue: '$5K - $25K',
          productCategory: 'Books & Media',
          budget: '$1K - $5K',
        },
      },
      {
        fullName: 'Tyler Brown',
        company: 'GamingStoreHub',
        title: 'Owner',
        email: 'tyler.b611@gamingstore.com',
        phone: '555-6111',
        status: 'CONTACTED',
        score: 87,
        customFields: {
          businessStage: 'Growing (6 months - 2 years)',
          platform: 'Shopify',
          serviceNeeded: 'Marketing/Advertising',
          monthlyRevenue: '$25K - $100K',
          productCategory: 'Gaming & Toys',
          budget: '$5K - $20K',
        },
      },
      {
        fullName: 'Laura Anderson',
        company: 'JewelryByLaura',
        title: 'Designer & Owner',
        email: 'laura.a612@jewelrybylaura.com',
        phone: '555-6112',
        status: 'QUALIFIED',
        score: 84,
        customFields: {
          businessStage: 'Established (2+ years)',
          platform: 'Etsy',
          serviceNeeded: 'SEO/Traffic',
          monthlyRevenue: '$5K - $25K',
          productCategory: 'Jewelry & Accessories',
          budget: '$1K - $5K',
        },
      },
      {
        fullName: 'Chris Taylor',
        company: 'ToolsAndHardwarePro',
        title: 'Managing Partner',
        email: 'chris.t613@toolspro.com',
        phone: '555-6113',
        status: 'NEW',
        score: 68,
        customFields: {
          businessStage: 'New (0-6 months)',
          platform: 'Amazon',
          serviceNeeded: 'Product sourcing',
          monthlyRevenue: 'Under $5K',
          productCategory: 'Tools & Hardware',
          budget: 'Under $1K',
        },
      },
      {
        fullName: 'Stephanie Lee',
        company: 'HealthSupplementsShop',
        title: 'CEO',
        email: 'stephanie.l614@healthsupplements.com',
        phone: '555-6114',
        status: 'CONTACTED',
        score: 91,
        customFields: {
          businessStage: 'Established (2+ years)',
          platform: 'Shopify',
          serviceNeeded: 'Fulfillment/Logistics',
          monthlyRevenue: '$100K - $500K',
          productCategory: 'Health & Wellness',
          budget: '$20K - $50K',
        },
      },
      {
        fullName: 'Michael Wang',
        company: 'VintageClothingCo',
        title: 'Founder',
        email: 'michael.w615@vintageclothing.com',
        phone: '555-6115',
        status: 'QUALIFIED',
        score: 89,
        customFields: {
          businessStage: 'Growing (6 months - 2 years)',
          platform: 'WooCommerce',
          serviceNeeded: 'Marketing/Advertising',
          monthlyRevenue: '$25K - $100K',
          productCategory: 'Fashion - Vintage',
          budget: '$5K - $20K',
        },
      },
    ],

    INSURANCE: [
      {
        fullName: 'Robert Williams',
        company: 'Individual',
        title: 'Family Provider',
        email: 'robert.w701@email.com',
        phone: '555-7101',
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          insuranceType: 'Life Insurance',
          coverageAmount: '$500K - $1M',
          currentCoverage: 'No coverage - first time',
          applicantAge: '35-44',
          healthStatus: 'Excellent',
          timeline: 'Immediate',
        },
      },
      {
        fullName: 'Jennifer Martinez',
        company: 'Individual',
        title: 'Self-Employed',
        email: 'jennifer.m702@email.com',
        phone: '555-7102',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          insuranceType: 'Health Insurance',
          coverageAmount: 'Not sure',
          currentCoverage: 'Coverage expired',
          applicantAge: '25-34',
          healthStatus: 'Good',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Michael Johnson',
        company: 'Individual',
        title: 'Homeowner',
        email: 'michael.j703@email.com',
        phone: '555-7103',
        status: 'NEW',
        score: 78,
        customFields: {
          insuranceType: 'Home/Property Insurance',
          coverageAmount: '$250K - $500K',
          currentCoverage: 'Have coverage - looking to replace',
          applicantAge: '45-54',
          healthStatus: 'Prefer not to say',
          timeline: '1-3 months',
        },
      },
      {
        fullName: 'Sarah Davis',
        company: 'Individual',
        title: 'Professional',
        email: 'sarah.d704@email.com',
        phone: '555-7104',
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          insuranceType: 'Disability Insurance',
          coverageAmount: '$100K - $250K',
          currentCoverage: 'No coverage - first time',
          applicantAge: '35-44',
          healthStatus: 'Excellent',
          timeline: 'Immediate',
        },
      },
      {
        fullName: 'David Lee',
        company: 'Small Business LLC',
        title: 'Business Owner',
        email: 'david.l705@email.com',
        phone: '555-7105',
        status: 'CONTACTED',
        score: 90,
        customFields: {
          insuranceType: 'Business Insurance',
          coverageAmount: 'Over $1M',
          currentCoverage: 'Have coverage - looking to add',
          applicantAge: '45-54',
          healthStatus: 'Good',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Lisa Anderson',
        company: 'Individual',
        title: 'Homeowner',
        email: 'lisa.a706@email.com',
        phone: '555-7106',
        status: 'NEW',
        score: 70,
        customFields: {
          insuranceType: 'Auto Insurance',
          coverageAmount: 'Not sure',
          currentCoverage: 'Have coverage - looking to replace',
          applicantAge: '25-34',
          healthStatus: 'Good',
          timeline: 'Just researching',
        },
      },
      {
        fullName: 'James Wilson',
        company: 'Individual',
        title: 'Retiree',
        email: 'james.w707@email.com',
        phone: '555-7107',
        status: 'QUALIFIED',
        score: 93,
        customFields: {
          insuranceType: 'Long-term Care',
          coverageAmount: '$250K - $500K',
          currentCoverage: 'No coverage - first time',
          applicantAge: '65+',
          healthStatus: 'Fair',
          timeline: 'Immediate',
        },
      },
      {
        fullName: 'Emily Brown',
        company: 'Individual',
        title: 'Young Professional',
        email: 'emily.b708@email.com',
        phone: '555-7108',
        status: 'CONTACTED',
        score: 82,
        customFields: {
          insuranceType: 'Life Insurance',
          coverageAmount: '$100K - $250K',
          currentCoverage: 'No coverage - first time',
          applicantAge: 'Under 25',
          healthStatus: 'Excellent',
          timeline: '1-3 months',
        },
      },
      {
        fullName: 'Thomas Garcia',
        company: 'Individual',
        title: 'Driver',
        email: 'thomas.g709@email.com',
        phone: '555-7109',
        status: 'NEW',
        score: 68,
        customFields: {
          insuranceType: 'Auto Insurance',
          coverageAmount: 'Under $100K',
          currentCoverage: 'Coverage expired',
          applicantAge: '25-34',
          healthStatus: 'Good',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Amanda Taylor',
        company: 'Individual',
        title: 'Family Provider',
        email: 'amanda.t710@email.com',
        phone: '555-7110',
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          insuranceType: 'Health Insurance',
          coverageAmount: 'Not sure',
          currentCoverage: 'No coverage - first time',
          applicantAge: '35-44',
          healthStatus: 'Pre-existing conditions',
          timeline: 'Immediate',
        },
      },
      {
        fullName: 'Kevin Rodriguez',
        company: 'Individual',
        title: 'Homeowner',
        email: 'kevin.r711@email.com',
        phone: '555-7111',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          insuranceType: 'Home/Property Insurance',
          coverageAmount: '$500K - $1M',
          currentCoverage: 'Have coverage - looking to add',
          applicantAge: '45-54',
          healthStatus: 'Good',
          timeline: '1-3 months',
        },
      },
      {
        fullName: 'Rachel White',
        company: 'Professional Services Inc',
        title: 'Partner',
        email: 'rachel.w712@email.com',
        phone: '555-7112',
        status: 'NEW',
        score: 75,
        customFields: {
          insuranceType: 'Business Insurance',
          coverageAmount: '$250K - $500K',
          currentCoverage: 'Not sure',
          applicantAge: '35-44',
          healthStatus: 'Good',
          timeline: 'Just researching',
        },
      },
      {
        fullName: 'Christopher Lee',
        company: 'Individual',
        title: 'Professional',
        email: 'chris.l713@email.com',
        phone: '555-7113',
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          insuranceType: 'Disability Insurance',
          coverageAmount: '$250K - $500K',
          currentCoverage: 'Have coverage - looking to replace',
          applicantAge: '35-44',
          healthStatus: 'Excellent',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Michelle Chen',
        company: 'Individual',
        title: 'Parent',
        email: 'michelle.c714@email.com',
        phone: '555-7114',
        status: 'CONTACTED',
        score: 91,
        customFields: {
          insuranceType: 'Life Insurance',
          coverageAmount: 'Over $1M',
          currentCoverage: 'Have coverage - looking to add',
          applicantAge: '35-44',
          healthStatus: 'Good',
          timeline: 'Immediate',
        },
      },
      {
        fullName: 'Daniel Martinez',
        company: 'Individual',
        title: 'Senior Citizen',
        email: 'daniel.m715@email.com',
        phone: '555-7115',
        status: 'QUALIFIED',
        score: 89,
        customFields: {
          insuranceType: 'Long-term Care',
          coverageAmount: '$100K - $250K',
          currentCoverage: 'No coverage - first time',
          applicantAge: '55-64',
          healthStatus: 'Fair',
          timeline: '1-3 months',
        },
      },
    ],

    SOLAR_ENERGY: [
      {
        fullName: 'Mark Thompson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'mark.t801@email.com',
        phone: '555-8101',
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$400 - $800',
          motivation: 'Save money',
          roofCondition: 'Good - no issues',
          timeline: 'Ready to install ASAP',
          financingPreference: 'Solar loan',
        },
      },
      {
        fullName: 'Jennifer Davis',
        company: 'Davis Manufacturing LLC',
        title: 'Facilities Director',
        email: 'jennifer.d802@business.com',
        phone: '555-8102',
        status: 'CONTACTED',
        score: 90,
        customFields: {
          propertyType: 'Industrial',
          ownership: 'Business owner',
          monthlyElectricBill: 'Over $800',
          motivation: 'Tax incentives',
          roofCondition: 'Excellent - new/recent',
          timeline: 'Next 1-3 months',
          financingPreference: 'Cash purchase',
        },
      },
      {
        fullName: 'Michael Johnson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'michael.j803@email.com',
        phone: '555-8103',
        status: 'NEW',
        score: 75,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$200 - $400',
          motivation: 'Environmental concerns',
          roofCondition: 'Fair - may need work soon',
          timeline: 'Just researching',
          financingPreference: 'Not sure yet',
        },
      },
      {
        fullName: 'Sarah Martinez',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'sarah.m804@email.com',
        phone: '555-8104',
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$400 - $800',
          motivation: 'Save money',
          roofCondition: 'Excellent - new/recent',
          timeline: 'Ready to install ASAP',
          financingPreference: 'Cash purchase',
        },
      },
      {
        fullName: 'David Lee',
        company: 'Green Valley Apartments',
        title: 'Property Manager',
        email: 'david.l805@apartments.com',
        phone: '555-8105',
        status: 'CONTACTED',
        score: 88,
        customFields: {
          propertyType: 'Residential - Multi Family',
          ownership: 'Property manager',
          monthlyElectricBill: 'Over $800',
          motivation: 'Increase property value',
          roofCondition: 'Good - no issues',
          timeline: 'Next 3-6 months',
          financingPreference: 'PPA (Power Purchase Agreement)',
        },
      },
      {
        fullName: 'Lisa Anderson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'lisa.a806@email.com',
        phone: '555-8106',
        status: 'NEW',
        score: 70,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$100 - $200',
          motivation: 'Environmental concerns',
          roofCondition: 'Not sure',
          timeline: 'Just researching',
          financingPreference: 'Not sure yet',
        },
      },
      {
        fullName: 'James Wilson',
        company: 'Wilson Farm LLC',
        title: 'Farm Owner',
        email: 'james.w807@farm.com',
        phone: '555-8107',
        status: 'QUALIFIED',
        score: 93,
        customFields: {
          propertyType: 'Agricultural',
          ownership: 'Business owner',
          monthlyElectricBill: 'Over $800',
          motivation: 'Save money',
          roofCondition: 'Good - no issues',
          timeline: 'Ready to install ASAP',
          financingPreference: 'Solar loan',
        },
      },
      {
        fullName: 'Emily Brown',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'emily.b808@email.com',
        phone: '555-8108',
        status: 'CONTACTED',
        score: 85,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$200 - $400',
          motivation: 'Energy independence',
          roofCondition: 'Good - no issues',
          timeline: 'Next 1-3 months',
          financingPreference: 'Lease',
        },
      },
      {
        fullName: 'Thomas Garcia',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'thomas.g809@email.com',
        phone: '555-8109',
        status: 'NEW',
        score: 72,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: 'Under $100',
          motivation: 'Tax incentives',
          roofCondition: 'Fair - may need work soon',
          timeline: 'Next 3-6 months',
          financingPreference: 'Not sure yet',
        },
      },
      {
        fullName: 'Amanda Taylor',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'amanda.t810@email.com',
        phone: '555-8110',
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$400 - $800',
          motivation: 'Save money',
          roofCondition: 'Excellent - new/recent',
          timeline: 'Next 1-3 months',
          financingPreference: 'Solar loan',
        },
      },
      {
        fullName: 'Kevin Rodriguez',
        company: 'Sunrise Office Park',
        title: 'Building Manager',
        email: 'kevin.r811@officepark.com',
        phone: '555-8111',
        status: 'CONTACTED',
        score: 87,
        customFields: {
          propertyType: 'Commercial Building',
          ownership: 'Property manager',
          monthlyElectricBill: 'Over $800',
          motivation: 'Tax incentives',
          roofCondition: 'Excellent - new/recent',
          timeline: 'Ready to install ASAP',
          financingPreference: 'PPA (Power Purchase Agreement)',
        },
      },
      {
        fullName: 'Rachel White',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'rachel.w812@email.com',
        phone: '555-8112',
        status: 'NEW',
        score: 68,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$100 - $200',
          motivation: 'Environmental concerns',
          roofCondition: 'Poor - needs replacement',
          timeline: 'Just researching',
          financingPreference: 'Not sure yet',
        },
      },
      {
        fullName: 'Christopher Lee',
        company: 'Tech Campus LLC',
        title: 'Operations Manager',
        email: 'chris.l813@techcampus.com',
        phone: '555-8113',
        status: 'QUALIFIED',
        score: 94,
        customFields: {
          propertyType: 'Commercial Building',
          ownership: 'Business owner',
          monthlyElectricBill: 'Over $800',
          motivation: 'Energy independence',
          roofCondition: 'Good - no issues',
          timeline: 'Ready to install ASAP',
          financingPreference: 'Cash purchase',
        },
      },
      {
        fullName: 'Michelle Chen',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'michelle.c814@email.com',
        phone: '555-8114',
        status: 'CONTACTED',
        score: 82,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$200 - $400',
          motivation: 'Increase property value',
          roofCondition: 'Good - no issues',
          timeline: 'Next 3-6 months',
          financingPreference: 'Solar loan',
        },
      },
      {
        fullName: 'Daniel Martinez',
        company: 'Homeowner',
        title: 'Homeowner',
        email: 'daniel.m815@email.com',
        phone: '555-8115',
        status: 'QUALIFIED',
        score: 91,
        customFields: {
          propertyType: 'Residential - Single Family',
          ownership: 'Own',
          monthlyElectricBill: '$400 - $800',
          motivation: 'Save money',
          roofCondition: 'Excellent - new/recent',
          timeline: 'Next 1-3 months',
          financingPreference: 'Cash purchase',
        },
      },
    ],
  };

  return sectorLeads[sector] || [];
}

function generateActivities(leadName: string, count: number) {
  const types = ['EMAIL', 'CALL', 'LINKEDIN', 'MEETING', 'NOTE'];
  const activities = [];

  const now = new Date();

  for (let i = 0; i < count; i++) {
    const type = types[Math.floor(Math.random() * types.length)];
    const daysAgo = Math.floor(Math.random() * 30) + 1;
    const activityDate = new Date(now.getTime() - (daysAgo * 24 * 60 * 60 * 1000));

    activities.push({
      type,
      content: `${type} activity with ${leadName}`,
      aiSummary: `Discussed project requirements and next steps with ${leadName}`,
      createdAt: activityDate,
    });
  }

  return activities.sort((a, b) => a.createdAt.getTime() - b.createdAt.getTime());
}
