// Helper to generate 15 realistic leads for each business sector with industry-specific custom fields

export function generateLeadsForSector(sector: string, startId: number = 101) {
  const statuses = ['NEW', 'CONTACTED', 'QUALIFIED', 'UNQUALIFIED'];
  const scores = [65, 70, 75, 78, 80, 82, 85, 87, 88, 90, 92, 95];

  const sectorLeads: Record<string, any[]> = {
    HOME_SERVICES: [
      {
        fullName: 'Sarah Johnson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `sarah.j${startId}@email.com`,
        phone: `555-01${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          projectDescription: 'AC unit stopped working completely, needs full replacement. House is 2500 sq ft.',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Replace/Install',
          urgency: 'Urgent (This week)',
          propertyOwnership: 'Own',
          budgetRange: '$5,000 - $15,000',
        },
      },
      {
        fullName: 'Michael Chen',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `michael.c${startId + 1}@email.com`,
        phone: `555-01${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 85,
        customFields: {
          projectDescription: 'Need new water heater installed, old one is leaking',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Replace/Install',
          urgency: 'Emergency (24-48 hours)',
          propertyOwnership: 'Own',
          budgetRange: '$1,000 - $5,000',
        },
      },
      {
        fullName: 'Emily Rodriguez',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `emily.r${startId + 2}@email.com`,
        phone: `555-01${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          projectDescription: 'Furnace making strange noises, needs inspection',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Repair',
          urgency: 'Normal (This month)',
          propertyOwnership: 'Own',
          budgetRange: 'Under $1,000',
        },
      },
      {
        fullName: 'David Martinez',
        company: 'Property Management Co',
        title: 'Property Manager',
        email: `david.m${startId + 3}@email.com`,
        phone: `555-01${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          projectDescription: 'Commercial building needs HVAC system upgrade for 5 units',
          propertyType: 'Commercial',
          serviceNeeded: 'Replace/Install',
          urgency: 'Planning (Future)',
          propertyOwnership: 'Property Manager',
          budgetRange: 'Over $50,000',
        },
      },
      {
        fullName: 'Lisa Anderson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `lisa.a${startId + 4}@email.com`,
        phone: `555-01${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          projectDescription: 'Toilet won\'t stop running, kitchen sink drain is slow',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Repair',
          urgency: 'Normal (This month)',
          propertyOwnership: 'Own',
          budgetRange: 'Under $1,000',
        },
      },
      {
        fullName: 'Robert Taylor',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `robert.t${startId + 5}@email.com`,
        phone: `555-01${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          projectDescription: 'Looking for HVAC maintenance contract for annual service',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Maintenance',
          urgency: 'Planning (Future)',
          propertyOwnership: 'Own',
          budgetRange: '$1,000 - $5,000',
        },
      },
      {
        fullName: 'Jennifer Williams',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `jennifer.w${startId + 6}@email.com`,
        phone: `555-01${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          projectDescription: 'Main sewer line backed up, needs emergency service',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Emergency Service',
          urgency: 'Emergency (24-48 hours)',
          propertyOwnership: 'Own',
          budgetRange: '$5,000 - $15,000',
        },
      },
      {
        fullName: 'James Brown',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `james.b${startId + 7}@email.com`,
        phone: `555-01${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          projectDescription: 'Installing new central air in home that currently has window units',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Replace/Install',
          urgency: 'Planning (Future)',
          propertyOwnership: 'Own',
          budgetRange: '$15,000 - $50,000',
        },
      },
      {
        fullName: 'Mary Garcia',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `mary.g${startId + 8}@email.com`,
        phone: `555-01${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          projectDescription: 'Water heater is 15 years old, looking for replacement options',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Consultation',
          urgency: 'Normal (This month)',
          propertyOwnership: 'Own',
          budgetRange: '$1,000 - $5,000',
        },
      },
      {
        fullName: 'William Davis',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `william.d${startId + 9}@email.com`,
        phone: `555-01${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          projectDescription: 'Need whole-house repiping, have galvanized pipes causing low pressure',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Replace/Install',
          urgency: 'Urgent (This week)',
          propertyOwnership: 'Own',
          budgetRange: '$15,000 - $50,000',
        },
      },
      {
        fullName: 'Patricia Miller',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `patricia.m${startId + 10}@email.com`,
        phone: `555-01${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          projectDescription: 'AC not cooling properly, might need refrigerant',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Repair',
          urgency: 'Urgent (This week)',
          propertyOwnership: 'Own',
          budgetRange: 'Under $1,000',
        },
      },
      {
        fullName: 'Richard Wilson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `richard.w${startId + 11}@email.com`,
        phone: `555-01${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          projectDescription: 'Garbage disposal broken, dishwasher not draining',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Repair',
          urgency: 'Normal (This month)',
          propertyOwnership: 'Own',
          budgetRange: 'Under $1,000',
        },
      },
      {
        fullName: 'Linda Moore',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `linda.m${startId + 12}@email.com`,
        phone: `555-01${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          projectDescription: 'New construction, need complete HVAC and plumbing for 3500 sq ft home',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Replace/Install',
          urgency: 'Planning (Future)',
          propertyOwnership: 'Own',
          budgetRange: 'Over $50,000',
        },
      },
      {
        fullName: 'Charles Taylor',
        company: 'Apartment Complex',
        title: 'Facilities Manager',
        email: `charles.t${startId + 13}@email.com`,
        phone: `555-01${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          projectDescription: 'Multiple units need water heater replacements',
          propertyType: 'Residential - Multi Family',
          serviceNeeded: 'Replace/Install',
          urgency: 'Normal (This month)',
          propertyOwnership: 'Property Manager',
          budgetRange: '$15,000 - $50,000',
        },
      },
      {
        fullName: 'Barbara Jackson',
        company: 'Homeowner',
        title: 'Homeowner',
        email: `barbara.j${startId + 14}@email.com`,
        phone: `555-01${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          projectDescription: 'Looking for energy-efficient AC upgrade, want consultation',
          propertyType: 'Residential - Single Family',
          serviceNeeded: 'Consultation',
          urgency: 'Planning (Future)',
          propertyOwnership: 'Own',
          budgetRange: '$5,000 - $15,000',
        },
      },
    ],

    LEGAL_SERVICES: [
      {
        fullName: 'Robert Williams',
        company: 'Individual',
        title: 'Prospective Client',
        email: `robert.w${startId}@email.com`,
        phone: `555-02${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          caseType: 'Personal Injury - Auto Accident',
          caseDescription: 'Rear-ended at red light, neck and back injuries',
          injurySeverity: 'Moderate',
          incidentDate: '2025-01-15',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Maria Garcia',
        company: 'Individual',
        title: 'Prospective Client',
        email: `maria.g${startId + 1}@email.com`,
        phone: `555-02${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 88,
        customFields: {
          caseType: 'Personal Injury - Slip & Fall',
          caseDescription: 'Slipped on wet floor in grocery store, broken wrist',
          injurySeverity: 'Moderate',
          incidentDate: '2025-01-20',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'James Thompson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `james.t${startId + 2}@email.com`,
        phone: `555-02${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          caseType: 'Family Law - Divorce',
          caseDescription: 'Contested divorce with property division',
          injurySeverity: 'Not applicable',
          incidentDate: '2025-02-01',
          insuranceCoverage: 'Not applicable',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Linda Martinez',
        company: 'Individual',
        title: 'Prospective Client',
        email: `linda.m${startId + 3}@email.com`,
        phone: `555-02${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          caseType: 'Personal Injury - Medical Malpractice',
          caseDescription: 'Surgical error resulting in complications',
          injurySeverity: 'Severe',
          incidentDate: '2024-12-10',
          insuranceCoverage: 'Yes - Have insurance',
          priorAttorney: 'Yes - consulted only',
        },
      },
      {
        fullName: 'David Chen',
        company: 'Individual',
        title: 'Prospective Client',
        email: `david.c${startId + 4}@email.com`,
        phone: `555-02${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          caseType: 'Personal Injury - Other',
          caseDescription: 'Construction site accident, multiple fractures',
          injurySeverity: 'Severe',
          incidentDate: '2025-01-05',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Susan Anderson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `susan.a${startId + 5}@email.com`,
        phone: `555-02${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          caseType: 'Family Law - Custody',
          caseDescription: 'Seeking primary custody of two children',
          injurySeverity: 'Not applicable',
          incidentDate: '2025-02-15',
          insuranceCoverage: 'Not applicable',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Michael Brown',
        company: 'Individual',
        title: 'Prospective Client',
        email: `michael.b${startId + 6}@email.com`,
        phone: `555-02${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 85,
        customFields: {
          caseType: 'Personal Injury - Other',
          caseDescription: 'Dog bite attack, facial injuries',
          injurySeverity: 'Moderate',
          incidentDate: '2025-01-25',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Patricia Davis',
        company: 'Individual',
        title: 'Prospective Client',
        email: `patricia.d${startId + 7}@email.com`,
        phone: `555-02${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          caseType: 'Personal Injury - Other',
          caseDescription: 'Defective product caused burns',
          injurySeverity: 'Moderate',
          incidentDate: '2025-01-18',
          insuranceCoverage: 'Yes - Have insurance',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'William Johnson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `william.j${startId + 8}@email.com`,
        phone: `555-02${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          caseType: 'Other',
          caseDescription: 'Employment dispute - wrongful termination',
          injurySeverity: 'Not applicable',
          incidentDate: '2025-02-10',
          insuranceCoverage: 'Not applicable',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Jennifer Wilson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `jennifer.w${startId + 9}@email.com`,
        phone: `555-02${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          caseType: 'Personal Injury - Auto Accident',
          caseDescription: 'Hit by car while cycling, broken leg',
          injurySeverity: 'Moderate',
          incidentDate: '2025-01-12',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Thomas Moore',
        company: 'Individual',
        title: 'Prospective Client',
        email: `thomas.m${startId + 10}@email.com`,
        phone: `555-02${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          caseType: 'Personal Injury - Auto Accident',
          caseDescription: 'Motorcycle accident, sideswiped by truck',
          injurySeverity: 'Severe',
          incidentDate: '2025-01-08',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Barbara Taylor',
        company: 'Individual',
        title: 'Prospective Client',
        email: `barbara.t${startId + 11}@email.com`,
        phone: `555-02${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          caseType: 'Estate Planning',
          caseDescription: 'Need to establish living trust for estate',
          injurySeverity: 'Not applicable',
          incidentDate: '2025-02-20',
          insuranceCoverage: 'Not applicable',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Richard Anderson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `richard.a${startId + 12}@email.com`,
        phone: `555-02${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          caseType: 'Personal Injury - Auto Accident',
          caseDescription: 'Semi-truck collision, catastrophic injuries',
          injurySeverity: 'Catastrophic',
          incidentDate: '2025-01-03',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Mary Jackson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `mary.j${startId + 13}@email.com`,
        phone: `555-02${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          caseType: 'Personal Injury - Auto Accident',
          caseDescription: 'Hit in crosswalk, leg and hip injuries',
          injurySeverity: 'Moderate',
          incidentDate: '2025-01-22',
          insuranceCoverage: 'Yes - Other party insured',
          priorAttorney: 'No',
        },
      },
      {
        fullName: 'Charles White',
        company: 'Individual',
        title: 'Prospective Client',
        email: `charles.w${startId + 14}@email.com`,
        phone: `555-02${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          caseType: 'Criminal Defense',
          caseDescription: 'DUI charge - first offense, need representation',
          injurySeverity: 'Not applicable',
          incidentDate: '2025-02-05',
          insuranceCoverage: 'Not applicable',
          priorAttorney: 'No',
        },
      },
    ],

    FINANCIAL_SERVICES: [
      {
        fullName: 'John Peterson',
        company: 'Individual',
        title: 'Prospective Client',
        email: `john.p${startId}@email.com`,
        phone: `555-03${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          serviceType: 'Life Insurance',
          coverageAmount: '$500K - $1M',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'Yes - looking to add',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Amanda Lee',
        company: 'Individual',
        title: 'Prospective Client',
        email: `amanda.l${startId + 1}@email.com`,
        phone: `555-03${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 85,
        customFields: {
          serviceType: 'Mortgage - Purchase',
          coverageAmount: '$250K - $500K',
          creditScoreRange: 'Good (680-719)',
          currentCoverage: 'No - first time',
          timeline: 'Soon (this month)',
        },
      },
      {
        fullName: 'Steven Cooper',
        company: 'Individual',
        title: 'Prospective Client',
        email: `steven.c${startId + 2}@email.com`,
        phone: `555-03${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          serviceType: 'Auto Insurance',
          coverageAmount: 'Under $100K',
          creditScoreRange: 'Good (680-719)',
          currentCoverage: 'Yes - looking to switch',
          timeline: 'Planning (1-3 months)',
        },
      },
      {
        fullName: 'Rachel Green',
        company: 'Individual',
        title: 'Prospective Client',
        email: `rachel.g${startId + 3}@email.com`,
        phone: `555-03${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          serviceType: 'Mortgage - Refinance',
          coverageAmount: '$250K - $500K',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'Yes - looking to switch',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Daniel Kim',
        company: 'Individual',
        title: 'Prospective Client',
        email: `daniel.k${startId + 4}@email.com`,
        phone: `555-03${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          serviceType: 'Investment Services',
          coverageAmount: '$100K - $250K',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'No - first time',
          timeline: 'Soon (this month)',
        },
      },
      {
        fullName: 'Michelle Ross',
        company: 'Individual',
        title: 'Prospective Client',
        email: `michelle.r${startId + 5}@email.com`,
        phone: `555-03${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          serviceType: 'Home Insurance',
          coverageAmount: '$250K - $500K',
          creditScoreRange: 'Good (680-719)',
          currentCoverage: 'Yes - looking to switch',
          timeline: 'Researching (3+ months)',
        },
      },
      {
        fullName: 'Christopher Hall',
        company: 'Individual',
        title: 'Prospective Client',
        email: `christopher.h${startId + 6}@email.com`,
        phone: `555-03${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          serviceType: 'Life Insurance',
          coverageAmount: 'Over $1M',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'Yes - looking to add',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Nicole Turner',
        company: 'Individual',
        title: 'Prospective Client',
        email: `nicole.t${startId + 7}@email.com`,
        phone: `555-03${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          serviceType: 'Personal Loan',
          coverageAmount: 'Under $100K',
          creditScoreRange: 'Fair (640-679)',
          currentCoverage: 'No - first time',
          timeline: 'Soon (this month)',
        },
      },
      {
        fullName: 'Brian Phillips',
        company: 'Individual',
        title: 'Prospective Client',
        email: `brian.p${startId + 8}@email.com`,
        phone: `555-03${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          serviceType: 'Health Insurance',
          coverageAmount: 'Not sure',
          creditScoreRange: 'Not sure',
          currentCoverage: 'No - first time',
          timeline: 'Planning (1-3 months)',
        },
      },
      {
        fullName: 'Angela Martinez',
        company: 'Individual',
        title: 'Prospective Client',
        email: `angela.m${startId + 9}@email.com`,
        phone: `555-03${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          serviceType: 'Mortgage - Purchase',
          coverageAmount: '$500K - $1M',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'No - first time',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Kevin Brown',
        company: 'Individual',
        title: 'Prospective Client',
        email: `kevin.b${startId + 10}@email.com`,
        phone: `555-03${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          serviceType: 'Investment Services',
          coverageAmount: '$250K - $500K',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'Yes - looking to add',
          timeline: 'Soon (this month)',
        },
      },
      {
        fullName: 'Stephanie Clark',
        company: 'Individual',
        title: 'Prospective Client',
        email: `stephanie.c${startId + 11}@email.com`,
        phone: `555-03${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          serviceType: 'Auto Insurance',
          coverageAmount: 'Under $100K',
          creditScoreRange: 'Fair (640-679)',
          currentCoverage: 'Yes - looking to switch',
          timeline: 'Researching (3+ months)',
        },
      },
      {
        fullName: 'Gregory Lewis',
        company: 'Individual',
        title: 'Prospective Client',
        email: `gregory.l${startId + 12}@email.com`,
        phone: `555-03${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          serviceType: 'Life Insurance',
          coverageAmount: 'Over $1M',
          creditScoreRange: 'Excellent (720+)',
          currentCoverage: 'No - first time',
          timeline: 'Immediate (this week)',
        },
      },
      {
        fullName: 'Rebecca Young',
        company: 'Individual',
        title: 'Prospective Client',
        email: `rebecca.y${startId + 13}@email.com`,
        phone: `555-03${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          serviceType: 'Mortgage - Refinance',
          coverageAmount: '$100K - $250K',
          creditScoreRange: 'Good (680-719)',
          currentCoverage: 'Yes - looking to switch',
          timeline: 'Soon (this month)',
        },
      },
      {
        fullName: 'Timothy Walker',
        company: 'Individual',
        title: 'Prospective Client',
        email: `timothy.w${startId + 14}@email.com`,
        phone: `555-03${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          serviceType: 'Personal Loan',
          coverageAmount: 'Under $100K',
          creditScoreRange: 'Good (680-719)',
          currentCoverage: 'No - first time',
          timeline: 'Planning (1-3 months)',
        },
      },
    ],

    REAL_ESTATE: [
      {
        fullName: 'Karen Thompson',
        company: 'Individual',
        title: 'Home Buyer',
        email: `karen.t${startId}@email.com`,
        phone: `555-04${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          lookingFor: 'Buy a home',
          location: 'Downtown Chicago, IL',
          priceRange: '$400K - $600K',
          timeline: 'Immediate (ready now)',
          preApproved: 'Yes - pre-approved',
          currentSituation: 'First-time buyer',
        },
      },
      {
        fullName: 'Paul Anderson',
        company: 'Individual',
        title: 'Home Seller',
        email: `paul.a${startId + 1}@email.com`,
        phone: `555-04${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 88,
        customFields: {
          lookingFor: 'Sell a home',
          location: 'Suburbs of Austin, TX',
          priceRange: '$600K - $800K',
          timeline: 'Soon (1-3 months)',
          preApproved: 'Not applicable',
          currentSituation: 'Relocating',
        },
      },
      {
        fullName: 'Deborah White',
        company: 'Individual',
        title: 'Home Buyer',
        email: `deborah.w${startId + 2}@email.com`,
        phone: `555-04${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          lookingFor: 'Buy a home',
          location: 'San Diego, CA',
          priceRange: 'Over $1M',
          timeline: 'Planning (3-6 months)',
          preApproved: 'In process',
          currentSituation: 'Upsizing',
        },
      },
      {
        fullName: 'Jason Lee',
        company: 'Individual',
        title: 'Investor',
        email: `jason.l${startId + 3}@email.com`,
        phone: `555-04${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          lookingFor: 'Investment property',
          location: 'Phoenix, AZ',
          priceRange: '$200K - $400K',
          timeline: 'Immediate (ready now)',
          preApproved: 'Cash buyer',
          currentSituation: 'Investor',
        },
      },
      {
        fullName: 'Sandra Hill',
        company: 'Individual',
        title: 'Home Buyer/Seller',
        email: `sandra.h${startId + 4}@email.com`,
        phone: `555-04${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          lookingFor: 'Buy & Sell',
          location: 'Denver, CO',
          priceRange: '$600K - $800K',
          timeline: 'Soon (1-3 months)',
          preApproved: 'Yes - pre-approved',
          currentSituation: 'Current homeowner',
        },
      },
      {
        fullName: 'Mark Davis',
        company: 'Small Business',
        title: 'Business Owner',
        email: `mark.d${startId + 5}@email.com`,
        phone: `555-04${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          lookingFor: 'Commercial property',
          location: 'Miami, FL',
          priceRange: 'Over $1M',
          timeline: 'Long-term (6+ months)',
          preApproved: 'Not yet',
          currentSituation: 'Other',
        },
      },
      {
        fullName: 'Laura Martin',
        company: 'Individual',
        title: 'Home Buyer',
        email: `laura.m${startId + 6}@email.com`,
        phone: `555-04${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 85,
        customFields: {
          lookingFor: 'Buy a home',
          location: 'Seattle, WA',
          priceRange: '$800K - $1M',
          timeline: 'Soon (1-3 months)',
          preApproved: 'Yes - pre-approved',
          currentSituation: 'First-time buyer',
        },
      },
      {
        fullName: 'Eric Thomas',
        company: 'Individual',
        title: 'Home Seller',
        email: `eric.t${startId + 7}@email.com`,
        phone: `555-04${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          lookingFor: 'Sell a home',
          location: 'Portland, OR',
          priceRange: '$400K - $600K',
          timeline: 'Immediate (ready now)',
          preApproved: 'Not applicable',
          currentSituation: 'Downsizing',
        },
      },
      {
        fullName: 'Donna Garcia',
        company: 'Individual',
        title: 'Renter',
        email: `donna.g${startId + 8}@email.com`,
        phone: `555-04${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          lookingFor: 'Rent/Lease',
          location: 'Boston, MA',
          priceRange: 'Not sure',
          timeline: 'Soon (1-3 months)',
          preApproved: 'Not applicable',
          currentSituation: 'Relocating',
        },
      },
      {
        fullName: 'George Rodriguez',
        company: 'Individual',
        title: 'Investor',
        email: `george.r${startId + 9}@email.com`,
        phone: `555-04${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          lookingFor: 'Investment property',
          location: 'Las Vegas, NV',
          priceRange: '$200K - $400K',
          timeline: 'Immediate (ready now)',
          preApproved: 'Cash buyer',
          currentSituation: 'Investor',
        },
      },
      {
        fullName: 'Cynthia Wilson',
        company: 'Individual',
        title: 'Home Buyer',
        email: `cynthia.w${startId + 10}@email.com`,
        phone: `555-04${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          lookingFor: 'Buy a home',
          location: 'Charlotte, NC',
          priceRange: '$400K - $600K',
          timeline: 'Planning (3-6 months)',
          preApproved: 'In process',
          currentSituation: 'Current homeowner',
        },
      },
      {
        fullName: 'Edward Martinez',
        company: 'Individual',
        title: 'Home Seller',
        email: `edward.m${startId + 11}@email.com`,
        phone: `555-04${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          lookingFor: 'Sell a home',
          location: 'Nashville, TN',
          priceRange: '$600K - $800K',
          timeline: 'Long-term (6+ months)',
          preApproved: 'Not applicable',
          currentSituation: 'Current homeowner',
        },
      },
      {
        fullName: 'Ruth Hernandez',
        company: 'Individual',
        title: 'Home Buyer',
        email: `ruth.h${startId + 12}@email.com`,
        phone: `555-04${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          lookingFor: 'Buy a home',
          location: 'Manhattan, NY',
          priceRange: 'Over $1M',
          timeline: 'Immediate (ready now)',
          preApproved: 'Yes - pre-approved',
          currentSituation: 'Upsizing',
        },
      },
      {
        fullName: 'Harold Moore',
        company: 'Individual',
        title: 'Home Buyer/Seller',
        email: `harold.m${startId + 13}@email.com`,
        phone: `555-04${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          lookingFor: 'Buy & Sell',
          location: 'Tampa, FL',
          priceRange: '$400K - $600K',
          timeline: 'Soon (1-3 months)',
          preApproved: 'Yes - pre-approved',
          currentSituation: 'Relocating',
        },
      },
      {
        fullName: 'Carol Taylor',
        company: 'Individual',
        title: 'Home Buyer',
        email: `carol.t${startId + 14}@email.com`,
        phone: `555-04${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          lookingFor: 'Buy a home',
          location: 'Raleigh, NC',
          priceRange: '$200K - $400K',
          timeline: 'Planning (3-6 months)',
          preApproved: 'Not yet',
          currentSituation: 'First-time buyer',
        },
      },
    ],

    HEALTHCARE: [
      {
        fullName: 'Dorothy Anderson',
        company: 'Individual',
        title: 'Patient',
        email: `dorothy.a${startId}@email.com`,
        phone: `555-05${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          serviceInterest: 'Dental - Cosmetic',
          insuranceStatus: 'No insurance - self-pay',
          urgency: 'Normal - willing to wait',
          preferredContact: 'Phone',
        },
      },
      {
        fullName: 'Gary Jackson',
        company: 'Individual',
        title: 'Patient',
        email: `gary.j${startId + 1}@email.com`,
        phone: `555-05${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 85,
        customFields: {
          serviceInterest: 'Physical Therapy',
          insuranceStatus: 'Have insurance',
          urgency: 'Urgent - need soon',
          preferredContact: 'Email',
        },
      },
      {
        fullName: 'Sharon White',
        company: 'Individual',
        title: 'Patient',
        email: `sharon.w${startId + 2}@email.com`,
        phone: `555-05${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          serviceInterest: 'Mental Health',
          insuranceStatus: 'Have insurance',
          urgency: 'Consultation only',
          preferredContact: 'Text message',
        },
      },
      {
        fullName: 'Larry King',
        company: 'Individual',
        title: 'Patient',
        email: `larry.k${startId + 3}@email.com`,
        phone: `555-05${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          serviceInterest: 'Weight Loss',
          insuranceStatus: 'No insurance - self-pay',
          urgency: 'Normal - willing to wait',
          preferredContact: 'Phone',
        },
      },
      {
        fullName: 'Betty Scott',
        company: 'Individual',
        title: 'Patient',
        email: `betty.s${startId + 4}@email.com`,
        phone: `555-05${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          serviceInterest: 'Dental - General',
          insuranceStatus: 'Have insurance',
          urgency: 'Urgent - need soon',
          preferredContact: 'Email',
        },
      },
      {
        fullName: 'Frank Green',
        company: 'Individual',
        title: 'Patient',
        email: `frank.g${startId + 5}@email.com`,
        phone: `555-05${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          serviceInterest: 'Addiction Treatment',
          insuranceStatus: 'Medicare/Medicaid',
          urgency: 'Just researching',
          preferredContact: 'No preference',
        },
      },
      {
        fullName: 'Helen Adams',
        company: 'Individual',
        title: 'Patient',
        email: `helen.a${startId + 6}@email.com`,
        phone: `555-05${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          serviceInterest: 'Plastic Surgery',
          insuranceStatus: 'No insurance - self-pay',
          urgency: 'Normal - willing to wait',
          preferredContact: 'Phone',
        },
      },
      {
        fullName: 'Arthur Baker',
        company: 'Individual',
        title: 'Patient',
        email: `arthur.b${startId + 7}@email.com`,
        phone: `555-05${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          serviceInterest: 'Physical Therapy',
          insuranceStatus: 'Have insurance',
          urgency: 'Urgent - need soon',
          preferredContact: 'Text message',
        },
      },
      {
        fullName: 'Teresa Nelson',
        company: 'Individual',
        title: 'Patient',
        email: `teresa.n${startId + 8}@email.com`,
        phone: `555-05${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          serviceInterest: 'Mental Health',
          insuranceStatus: 'Have insurance',
          urgency: 'Normal - willing to wait',
          preferredContact: 'Email',
        },
      },
      {
        fullName: 'Jack Mitchell',
        company: 'Individual',
        title: 'Patient',
        email: `jack.m${startId + 9}@email.com`,
        phone: `555-05${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          serviceInterest: 'Dental - Cosmetic',
          insuranceStatus: 'No insurance - self-pay',
          urgency: 'Consultation only',
          preferredContact: 'Phone',
        },
      },
      {
        fullName: 'Shirley Carter',
        company: 'Individual',
        title: 'Patient',
        email: `shirley.c${startId + 10}@email.com`,
        phone: `555-05${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          serviceInterest: 'Weight Loss',
          insuranceStatus: 'Have insurance',
          urgency: 'Urgent - need soon',
          preferredContact: 'Text message',
        },
      },
      {
        fullName: 'Ralph Roberts',
        company: 'Individual',
        title: 'Patient',
        email: `ralph.r${startId + 11}@email.com`,
        phone: `555-05${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          serviceInterest: 'Other',
          insuranceStatus: 'Not sure',
          urgency: 'Just researching',
          preferredContact: 'No preference',
        },
      },
      {
        fullName: 'Virginia Phillips',
        company: 'Individual',
        title: 'Patient',
        email: `virginia.p${startId + 12}@email.com`,
        phone: `555-05${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          serviceInterest: 'Plastic Surgery',
          insuranceStatus: 'No insurance - self-pay',
          urgency: 'Urgent - need soon',
          preferredContact: 'Phone',
        },
      },
      {
        fullName: 'Carl Campbell',
        company: 'Individual',
        title: 'Patient',
        email: `carl.c${startId + 13}@email.com`,
        phone: `555-05${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          serviceInterest: 'Dental - General',
          insuranceStatus: 'Have insurance',
          urgency: 'Normal - willing to wait',
          preferredContact: 'Email',
        },
      },
      {
        fullName: 'Evelyn Parker',
        company: 'Individual',
        title: 'Patient',
        email: `evelyn.p${startId + 14}@email.com`,
        phone: `555-05${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          serviceInterest: 'Mental Health',
          insuranceStatus: 'Medicare/Medicaid',
          urgency: 'Consultation only',
          preferredContact: 'Phone',
        },
      },
    ],

    B2B_SAAS: [
      {
        fullName: 'Roy Evans',
        company: 'TechCorp Solutions',
        title: 'CTO',
        email: `roy.e${startId}@techcorp.com`,
        phone: `555-06${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          companySize: '51-200 employees',
          industry: 'Software Development',
          currentSolution: 'Using competitor',
          budget: '$100K - $500K',
          timeline: 'Immediate',
          decisionMaker: 'Decision maker',
        },
      },
      {
        fullName: 'Alice Edwards',
        company: 'FinanceHub Inc',
        title: 'VP of Operations',
        email: `alice.e${startId + 1}@financehub.com`,
        phone: `555-06${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 88,
        customFields: {
          companySize: '201-500 employees',
          industry: 'Finance',
          currentSolution: 'Using in-house solution',
          budget: '$50K - $100K',
          timeline: '1-3 months',
          decisionMaker: 'Influencer',
        },
      },
      {
        fullName: 'Dennis Collins',
        company: 'RetailMax',
        title: 'IT Director',
        email: `dennis.c${startId + 2}@retailmax.com`,
        phone: `555-06${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          companySize: '500+ employees',
          industry: 'Retail',
          currentSolution: 'Using spreadsheets',
          budget: 'Not determined',
          timeline: 'Just researching',
          decisionMaker: 'Evaluator/Researcher',
        },
      },
      {
        fullName: 'Joan Stewart',
        company: 'HealthFirst Medical',
        title: 'CFO',
        email: `joan.s${startId + 3}@healthfirst.com`,
        phone: `555-06${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          companySize: '201-500 employees',
          industry: 'Healthcare',
          currentSolution: 'No current solution',
          budget: '$100K - $500K',
          timeline: 'Immediate',
          decisionMaker: 'Decision maker',
        },
      },
      {
        fullName: 'Randy Sanchez',
        company: 'Logistics Pro',
        title: 'Operations Manager',
        email: `randy.s${startId + 4}@logisticspro.com`,
        phone: `555-06${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          companySize: '51-200 employees',
          industry: 'Logistics',
          currentSolution: 'Using competitor',
          budget: '$50K - $100K',
          timeline: '3-6 months',
          decisionMaker: 'Influencer',
        },
      },
      {
        fullName: 'Kathleen Morris',
        company: 'EduTech Systems',
        title: 'Product Manager',
        email: `kathleen.m${startId + 5}@edutech.com`,
        phone: `555-06${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          companySize: '11-50 employees',
          industry: 'Education Technology',
          currentSolution: 'Other',
          budget: 'Under $10K',
          timeline: '6-12 months',
          decisionMaker: 'End user',
        },
      },
      {
        fullName: 'Albert Rogers',
        company: 'Manufacturing Plus',
        title: 'CIO',
        email: `albert.r${startId + 6}@mfgplus.com`,
        phone: `555-06${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 85,
        customFields: {
          companySize: '500+ employees',
          industry: 'Manufacturing',
          currentSolution: 'Using in-house solution',
          budget: 'Over $500K',
          timeline: '1-3 months',
          decisionMaker: 'Decision maker',
        },
      },
      {
        fullName: 'Janice Reed',
        company: 'Marketing Pros',
        title: 'Marketing Director',
        email: `janice.r${startId + 7}@marketingpros.com`,
        phone: `555-06${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          companySize: '11-50 employees',
          industry: 'Marketing',
          currentSolution: 'Using spreadsheets',
          budget: '$10K - $50K',
          timeline: '1-3 months',
          decisionMaker: 'Influencer',
        },
      },
      {
        fullName: 'Eugene Cook',
        company: 'Insurance Direct',
        title: 'VP of Technology',
        email: `eugene.c${startId + 8}@insurancedirect.com`,
        phone: `555-06${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          companySize: '201-500 employees',
          industry: 'Insurance',
          currentSolution: 'Using competitor',
          budget: 'Not determined',
          timeline: 'Just researching',
          decisionMaker: 'Evaluator/Researcher',
        },
      },
      {
        fullName: 'Carolyn Morgan',
        company: 'Construction Tech',
        title: 'CEO',
        email: `carolyn.m${startId + 9}@constructiontech.com`,
        phone: `555-06${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          companySize: '51-200 employees',
          industry: 'Construction',
          currentSolution: 'No current solution',
          budget: '$50K - $100K',
          timeline: 'Immediate',
          decisionMaker: 'Decision maker',
        },
      },
      {
        fullName: 'Ralph Bailey',
        company: 'Hospitality Systems',
        title: 'IT Manager',
        email: `ralph.b${startId + 10}@hospitalitysys.com`,
        phone: `555-06${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          companySize: '11-50 employees',
          industry: 'Hospitality',
          currentSolution: 'Using spreadsheets',
          budget: '$10K - $50K',
          timeline: '3-6 months',
          decisionMaker: 'Influencer',
        },
      },
      {
        fullName: 'Jean Rivera',
        company: 'Energy Solutions',
        title: 'Director of Operations',
        email: `jean.r${startId + 11}@energysol.com`,
        phone: `555-06${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          companySize: '500+ employees',
          industry: 'Energy',
          currentSolution: 'Using in-house solution',
          budget: 'Over $500K',
          timeline: '6-12 months',
          decisionMaker: 'Evaluator/Researcher',
        },
      },
      {
        fullName: 'Keith Cooper',
        company: 'Legal Tech Group',
        title: 'CTO',
        email: `keith.c${startId + 12}@legaltech.com`,
        phone: `555-06${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          companySize: '201-500 employees',
          industry: 'Legal Services',
          currentSolution: 'Using competitor',
          budget: '$100K - $500K',
          timeline: 'Immediate',
          decisionMaker: 'Decision maker',
        },
      },
      {
        fullName: 'Martha Richardson',
        company: 'Consulting Partners',
        title: 'Managing Partner',
        email: `martha.r${startId + 13}@consultingp.com`,
        phone: `555-06${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          companySize: '11-50 employees',
          industry: 'Consulting',
          currentSolution: 'Other',
          budget: '$10K - $50K',
          timeline: '1-3 months',
          decisionMaker: 'Decision maker',
        },
      },
      {
        fullName: 'Willie Cox',
        company: 'Transportation Hub',
        title: 'VP of Operations',
        email: `willie.c${startId + 14}@transporthub.com`,
        phone: `555-06${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          companySize: '51-200 employees',
          industry: 'Transportation',
          currentSolution: 'No current solution',
          budget: 'Not determined',
          timeline: 'Just researching',
          decisionMaker: 'End user',
        },
      },
    ],

    EDUCATION: [
      {
        fullName: 'Gloria Howard',
        company: 'Individual',
        title: 'Prospective Student',
        email: `gloria.h${startId}@email.com`,
        phone: `555-07${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          programInterest: 'MBA',
          educationLevel: 'Bachelor Degree',
          studyPreference: 'Hybrid',
          startDate: 'Next term',
        },
      },
      {
        fullName: 'Jerry Ward',
        company: 'Individual',
        title: 'Prospective Student',
        email: `jerry.w${startId + 1}@email.com`,
        phone: `555-07${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 85,
        customFields: {
          programInterest: 'Software Development',
          educationLevel: 'Some College',
          studyPreference: 'Online',
          startDate: '3-6 months',
        },
      },
      {
        fullName: 'Kathryn Torres',
        company: 'Individual',
        title: 'Prospective Student',
        email: `kathryn.t${startId + 2}@email.com`,
        phone: `555-07${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          programInterest: 'Nursing',
          educationLevel: 'High School',
          studyPreference: 'In-person',
          startDate: 'Not sure',
        },
      },
      {
        fullName: 'Philip Peterson',
        company: 'Individual',
        title: 'Prospective Student',
        email: `philip.p${startId + 3}@email.com`,
        phone: `555-07${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          programInterest: 'Data Science',
          educationLevel: 'Bachelor Degree',
          studyPreference: 'Online',
          startDate: 'Next term',
        },
      },
      {
        fullName: 'Annie Gray',
        company: 'Individual',
        title: 'Prospective Student',
        email: `annie.g${startId + 4}@email.com`,
        phone: `555-07${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          programInterest: 'Marketing',
          educationLevel: 'Associate Degree',
          studyPreference: 'Hybrid',
          startDate: '3-6 months',
        },
      },
      {
        fullName: 'Roger Ramirez',
        company: 'Individual',
        title: 'Prospective Student',
        email: `roger.r${startId + 5}@email.com`,
        phone: `555-07${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          programInterest: 'Graphic Design',
          educationLevel: 'High School',
          studyPreference: 'Online',
          startDate: '6-12 months',
        },
      },
      {
        fullName: 'Judy James',
        company: 'Individual',
        title: 'Prospective Student',
        email: `judy.j${startId + 6}@email.com`,
        phone: `555-07${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          programInterest: 'Healthcare Administration',
          educationLevel: 'Master Degree',
          studyPreference: 'Online',
          startDate: 'Next term',
        },
      },
      {
        fullName: 'Russell Watson',
        company: 'Individual',
        title: 'Prospective Student',
        email: `russell.w${startId + 7}@email.com`,
        phone: `555-07${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          programInterest: 'Cybersecurity',
          educationLevel: 'Bachelor Degree',
          studyPreference: 'Hybrid',
          startDate: '3-6 months',
        },
      },
      {
        fullName: 'Beverly Brooks',
        company: 'Individual',
        title: 'Prospective Student',
        email: `beverly.b${startId + 8}@email.com`,
        phone: `555-07${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          programInterest: 'Teaching',
          educationLevel: 'Bachelor Degree',
          studyPreference: 'In-person',
          startDate: 'Not sure',
        },
      },
      {
        fullName: 'Peter Kelly',
        company: 'Individual',
        title: 'Prospective Student',
        email: `peter.k${startId + 9}@email.com`,
        phone: `555-07${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          programInterest: 'Project Management',
          educationLevel: 'Bachelor Degree',
          studyPreference: 'Online',
          startDate: 'Next term',
        },
      },
      {
        fullName: 'Denise Sanders',
        company: 'Individual',
        title: 'Prospective Student',
        email: `denise.s${startId + 10}@email.com`,
        phone: `555-07${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          programInterest: 'Accounting',
          educationLevel: 'Associate Degree',
          studyPreference: 'Hybrid',
          startDate: '3-6 months',
        },
      },
      {
        fullName: 'Aaron Price',
        company: 'Individual',
        title: 'Prospective Student',
        email: `aaron.p${startId + 11}@email.com`,
        phone: `555-07${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          programInterest: 'Culinary Arts',
          educationLevel: 'High School',
          studyPreference: 'In-person',
          startDate: 'Not sure',
        },
      },
      {
        fullName: 'Judy Bennett',
        company: 'Individual',
        title: 'Prospective Student',
        email: `judy.b${startId + 12}@email.com`,
        phone: `555-07${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          programInterest: 'PhD in Psychology',
          educationLevel: 'Master Degree',
          studyPreference: 'Hybrid',
          startDate: 'Next term',
        },
      },
      {
        fullName: 'Jose Wood',
        company: 'Individual',
        title: 'Prospective Student',
        email: `jose.w${startId + 13}@email.com`,
        phone: `555-07${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          programInterest: 'UX Design',
          educationLevel: 'Some College',
          studyPreference: 'Online',
          startDate: '3-6 months',
        },
      },
      {
        fullName: 'Lori Barnes',
        company: 'Individual',
        title: 'Prospective Student',
        email: `lori.b${startId + 14}@email.com`,
        phone: `555-07${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          programInterest: 'Human Resources',
          educationLevel: 'Bachelor Degree',
          studyPreference: 'No preference',
          startDate: '6-12 months',
        },
      },
    ],

    AUTOMOTIVE: [
      {
        fullName: 'Wayne Ross',
        company: 'Individual',
        title: 'Car Buyer',
        email: `wayne.r${startId}@email.com`,
        phone: `555-08${String(startId).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 92,
        customFields: {
          interestType: 'Buy new car',
          vehicleType: 'SUV',
          budgetRange: '$50K - $75K',
          timeline: 'This week',
        },
      },
      {
        fullName: 'Theresa Henderson',
        company: 'Individual',
        title: 'Car Buyer',
        email: `theresa.h${startId + 1}@email.com`,
        phone: `555-08${String(startId + 1).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 85,
        customFields: {
          interestType: 'Buy used car',
          vehicleType: 'Sedan',
          budgetRange: '$20K - $35K',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Judy Coleman',
        company: 'Individual',
        title: 'Car Buyer',
        email: `judy.c${startId + 2}@email.com`,
        phone: `555-08${String(startId + 2).padStart(2, '0')}`,
        status: 'NEW',
        score: 72,
        customFields: {
          interestType: 'Lease',
          vehicleType: 'Electric',
          budgetRange: 'Not sure',
          timeline: 'Just looking',
        },
      },
      {
        fullName: 'Johnny Jenkins',
        company: 'Individual',
        title: 'Car Owner',
        email: `johnny.j${startId + 3}@email.com`,
        phone: `555-08${String(startId + 3).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 88,
        customFields: {
          interestType: 'Service/Repair',
          vehicleType: 'Truck',
          budgetRange: 'Under $20K',
          timeline: 'This week',
        },
      },
      {
        fullName: 'Frances Perry',
        company: 'Individual',
        title: 'Car Buyer',
        email: `frances.p${startId + 4}@email.com`,
        phone: `555-08${String(startId + 4).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 80,
        customFields: {
          interestType: 'Buy new car',
          vehicleType: 'Hybrid',
          budgetRange: '$35K - $50K',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Jeremy Powell',
        company: 'Individual',
        title: 'Car Owner',
        email: `jeremy.p${startId + 5}@email.com`,
        phone: `555-08${String(startId + 5).padStart(2, '0')}`,
        status: 'NEW',
        score: 68,
        customFields: {
          interestType: 'Trade-in',
          vehicleType: 'Sedan',
          budgetRange: '$20K - $35K',
          timeline: '1-3 months',
        },
      },
      {
        fullName: 'Christina Long',
        company: 'Individual',
        title: 'Car Buyer',
        email: `christina.l${startId + 6}@email.com`,
        phone: `555-08${String(startId + 6).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 90,
        customFields: {
          interestType: 'Buy new car',
          vehicleType: 'Sports car',
          budgetRange: 'Over $75K',
          timeline: 'This week',
        },
      },
      {
        fullName: 'Raymond Patterson',
        company: 'Individual',
        title: 'Car Buyer',
        email: `raymond.p${startId + 7}@email.com`,
        phone: `555-08${String(startId + 7).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 76,
        customFields: {
          interestType: 'Buy used car',
          vehicleType: 'Truck',
          budgetRange: '$35K - $50K',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Joyce Hughes',
        company: 'Individual',
        title: 'Car Buyer',
        email: `joyce.h${startId + 8}@email.com`,
        phone: `555-08${String(startId + 8).padStart(2, '0')}`,
        status: 'NEW',
        score: 70,
        customFields: {
          interestType: 'Lease',
          vehicleType: 'Van',
          budgetRange: '$20K - $35K',
          timeline: 'Just looking',
        },
      },
      {
        fullName: 'Gerald Flores',
        company: 'Individual',
        title: 'Car Buyer',
        email: `gerald.f${startId + 9}@email.com`,
        phone: `555-08${String(startId + 9).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 87,
        customFields: {
          interestType: 'Buy new car',
          vehicleType: 'Electric',
          budgetRange: '$50K - $75K',
          timeline: 'This week',
        },
      },
      {
        fullName: 'Cheryl Washington',
        company: 'Individual',
        title: 'Car Owner',
        email: `cheryl.w${startId + 10}@email.com`,
        phone: `555-08${String(startId + 10).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 82,
        customFields: {
          interestType: 'Service/Repair',
          vehicleType: 'SUV',
          budgetRange: 'Under $20K',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Carl Butler',
        company: 'Individual',
        title: 'Car Buyer',
        email: `carl.b${startId + 11}@email.com`,
        phone: `555-08${String(startId + 11).padStart(2, '0')}`,
        status: 'NEW',
        score: 65,
        customFields: {
          interestType: 'Other',
          vehicleType: 'Other',
          budgetRange: 'Not sure',
          timeline: 'Just looking',
        },
      },
      {
        fullName: 'Mildred Simmons',
        company: 'Individual',
        title: 'Car Buyer',
        email: `mildred.s${startId + 12}@email.com`,
        phone: `555-08${String(startId + 12).padStart(2, '0')}`,
        status: 'QUALIFIED',
        score: 95,
        customFields: {
          interestType: 'Buy new car',
          vehicleType: 'SUV',
          budgetRange: 'Over $75K',
          timeline: 'This week',
        },
      },
      {
        fullName: 'Victor Foster',
        company: 'Individual',
        title: 'Car Buyer',
        email: `victor.f${startId + 13}@email.com`,
        phone: `555-08${String(startId + 13).padStart(2, '0')}`,
        status: 'CONTACTED',
        score: 78,
        customFields: {
          interestType: 'Buy used car',
          vehicleType: 'Hybrid',
          budgetRange: '$35K - $50K',
          timeline: 'This month',
        },
      },
      {
        fullName: 'Janet Bryant',
        company: 'Individual',
        title: 'Car Owner',
        email: `janet.b${startId + 14}@email.com`,
        phone: `555-08${String(startId + 14).padStart(2, '0')}`,
        status: 'NEW',
        score: 75,
        customFields: {
          interestType: 'Trade-in',
          vehicleType: 'Sedan',
          budgetRange: '$20K - $35K',
          timeline: '1-3 months',
        },
      },
    ],
  };

  return sectorLeads[sector] || [];
}

// Helper to generate realistic activities for leads based on business sector
export function generateActivitiesForSector(sector: string, leadIndex: number = 0) {
  const activityTypes = ['EMAIL', 'CALL', 'LINKEDIN', 'MEETING', 'NOTE'];

  const sectorActivities: Record<string, any[]> = {
    HOME_SERVICES: [
      { type: 'CALL', content: 'Initial contact call - Customer inquired about HVAC replacement pricing.' },
      { type: 'EMAIL', content: 'Sent detailed quote for HVAC system replacement including labor and materials.' },
      { type: 'CALL', content: 'Follow-up call - Discussed financing options and answered technical questions.' },
      { type: 'MEETING', content: 'On-site inspection scheduled for property assessment and measurements.' },
      { type: 'EMAIL', content: 'Sent revised quote with financing terms and installation timeline.' },
      { type: 'CALL', content: 'Customer requested references from previous HVAC installations in area.' },
      { type: 'EMAIL', content: 'Provided 5 customer references and photo gallery of completed projects.' },
      { type: 'NOTE', content: 'Customer comparing quotes from 2 other contractors - price is competitive.' },
      { type: 'CALL', content: 'Follow-up on quote - Customer has budget approved, ready to schedule.' },
      { type: 'EMAIL', content: 'Sent installation contract and schedule for next week.' },
      { type: 'MEETING', content: 'Pre-installation walkthrough to confirm equipment placement and logistics.' },
      { type: 'NOTE', content: 'Customer requested energy efficiency rebate information - sent documentation.' },
      { type: 'CALL', content: 'Confirmed installation date and discussed preparation requirements.' },
      { type: 'EMAIL', content: 'Sent reminder email with installation checklist and what to expect.' },
      { type: 'NOTE', content: 'Ready to close - installation scheduled for next Tuesday at 8am.' },
    ],

    LEGAL_SERVICES: [
      { type: 'CALL', content: 'Initial consultation - Discussed auto accident case and injuries sustained.' },
      { type: 'NOTE', content: 'Client has medical records documenting neck and back injuries from accident.' },
      { type: 'EMAIL', content: 'Sent retainer agreement and intake questionnaire for case evaluation.' },
      { type: 'CALL', content: 'Reviewed police report and witness statements with client.' },
      { type: 'MEETING', content: 'In-person meeting to sign retainer and discuss case strategy.' },
      { type: 'EMAIL', content: 'Requested additional medical documentation and treatment records.' },
      { type: 'NOTE', content: 'Filed demand letter with insurance company for $150K settlement.' },
      { type: 'CALL', content: 'Insurance adjuster responded with initial offer of $45K - rejected.' },
      { type: 'EMAIL', content: 'Sent counter-offer documentation with expert medical opinions.' },
      { type: 'MEETING', content: 'Strategy session - Discussed litigation vs settlement options.' },
      { type: 'CALL', content: 'Insurance increased offer to $85K - client considering.' },
      { type: 'NOTE', content: 'Prepared case for trial filing if settlement negotiations fail.' },
      { type: 'EMAIL', content: 'Sent settlement comparison analysis showing trial vs settlement outcomes.' },
      { type: 'CALL', content: 'Client approved counter-offer of $110K to settle case.' },
      { type: 'NOTE', content: 'Settlement agreement finalized - closing in 30 days.' },
    ],

    FINANCIAL_SERVICES: [
      { type: 'CALL', content: 'Initial inquiry about life insurance coverage for family protection.' },
      { type: 'EMAIL', content: 'Sent life insurance quote comparison for term vs whole life policies.' },
      { type: 'MEETING', content: 'Needs analysis appointment - Reviewed financial goals and coverage needs.' },
      { type: 'NOTE', content: 'Client needs $750K coverage, prefers 30-year term policy.' },
      { type: 'EMAIL', content: 'Submitted application for medical underwriting review.' },
      { type: 'CALL', content: 'Medical exam scheduled - Sent instructions and what to expect.' },
      { type: 'NOTE', content: 'Underwriting approved at standard rates - excellent health profile.' },
      { type: 'EMAIL', content: 'Sent policy documents for review and signature.' },
      { type: 'CALL', content: 'Reviewed policy terms, beneficiaries, and premium payment options.' },
      { type: 'MEETING', content: 'Policy delivery appointment - Explained coverage and answered questions.' },
      { type: 'EMAIL', content: 'Sent welcome packet with policy number and online account access.' },
      { type: 'NOTE', content: 'Client enrolled in automatic premium payments from checking account.' },
      { type: 'CALL', content: 'Follow-up on other insurance needs - Discussing mortgage protection.' },
      { type: 'EMAIL', content: 'Sent mortgage protection insurance quote and benefit comparison.' },
      { type: 'NOTE', content: 'Policy active - Scheduled annual review in 12 months.' },
    ],

    REAL_ESTATE: [
      { type: 'CALL', content: 'First-time home buyer inquiry - Looking in downtown area.' },
      { type: 'EMAIL', content: 'Sent mortgage pre-approval checklist and lender recommendations.' },
      { type: 'MEETING', content: 'Buyer consultation - Discussed budget, neighborhoods, and home preferences.' },
      { type: 'NOTE', content: 'Client pre-approved for $500K, wants 3BR/2BA single family home.' },
      { type: 'EMAIL', content: 'Sent 8 property listings matching criteria with virtual tour links.' },
      { type: 'CALL', content: 'Scheduled showing appointments for 5 properties this weekend.' },
      { type: 'MEETING', content: 'Property showings - Visited 5 homes, client loved 2 of them.' },
      { type: 'NOTE', content: 'Preparing offer on 123 Main St - Listed at $485K, offering $475K.' },
      { type: 'EMAIL', content: 'Sent offer package to listing agent with pre-approval letter.' },
      { type: 'CALL', content: 'Received counter-offer at $480K - Discussing with client.' },
      { type: 'EMAIL', content: 'Client accepted counter-offer - Sent signed acceptance.' },
      { type: 'MEETING', content: 'Inspection scheduled for Wednesday - Reviewed inspection process.' },
      { type: 'NOTE', content: 'Home inspection revealed minor repairs needed - Requesting $3K credit.' },
      { type: 'CALL', content: 'Seller agreed to $2K credit - Proceeding to appraisal.' },
      { type: 'EMAIL', content: 'Appraisal complete at $485K - Closing scheduled for next Friday.' },
    ],

    HEALTHCARE: [
      { type: 'CALL', content: 'New patient inquiry about cosmetic dentistry services.' },
      { type: 'EMAIL', content: 'Sent information packet about teeth whitening and veneers options.' },
      { type: 'MEETING', content: 'Initial consultation - Examined teeth and discussed treatment goals.' },
      { type: 'NOTE', content: 'Patient interested in professional whitening and 6 veneers for smile makeover.' },
      { type: 'EMAIL', content: 'Sent treatment plan with cost breakdown and before/after examples.' },
      { type: 'CALL', content: 'Discussed insurance coverage and payment plan options.' },
      { type: 'NOTE', content: 'Insurance covers preventive only - Arranged 12-month payment plan.' },
      { type: 'EMAIL', content: 'Sent financial agreement and scheduled first appointment.' },
      { type: 'MEETING', content: 'Teeth impressions taken for veneer fabrication - Whitening started.' },
      { type: 'CALL', content: 'Follow-up on whitening progress - Discussed sensitivity management.' },
      { type: 'EMAIL', content: 'Sent care instructions and scheduled veneer placement appointment.' },
      { type: 'MEETING', content: 'Veneer placement completed - Patient extremely happy with results.' },
      { type: 'NOTE', content: 'Scheduled 6-month follow-up for routine cleaning and check.' },
      { type: 'CALL', content: 'Patient referred 2 friends for cosmetic consultations.' },
      { type: 'EMAIL', content: 'Sent referral thank you note with $50 credit for future services.' },
    ],

    B2B_SAAS: [
      { type: 'EMAIL', content: 'Inbound demo request from CTO - Interested in workflow automation.' },
      { type: 'CALL', content: 'Discovery call - Discussed current pain points and manual processes.' },
      { type: 'NOTE', content: 'Company has 150 employees, using spreadsheets for project management.' },
      { type: 'EMAIL', content: 'Sent case study from similar-sized company that achieved 40% efficiency gain.' },
      { type: 'MEETING', content: 'Product demo with CTO and Operations team - Showed key features.' },
      { type: 'CALL', content: 'Follow-up on demo - Addressed technical questions about integrations.' },
      { type: 'EMAIL', content: 'Sent custom proposal with pricing for 150 users and implementation plan.' },
      { type: 'NOTE', content: 'Decision timeline is 2 months - Evaluating 2 other competitors.' },
      { type: 'MEETING', content: 'Technical deep-dive with IT team - Reviewed security and API capabilities.' },
      { type: 'CALL', content: 'Negotiating contract terms - Discussing annual vs 3-year commitment.' },
      { type: 'EMAIL', content: 'Sent revised proposal with volume discount and free training package.' },
      { type: 'MEETING', content: 'Executive presentation to C-suite - Presented ROI analysis.' },
      { type: 'NOTE', content: 'Internal champion pushing for approval - Budget allocated for Q2.' },
      { type: 'CALL', content: 'Received verbal commitment - Legal reviewing contract terms.' },
      { type: 'EMAIL', content: 'Sent final contract with implementation timeline starting April 1st.' },
    ],

    EDUCATION: [
      { type: 'CALL', content: 'Prospective student inquiry about coding bootcamp program.' },
      { type: 'EMAIL', content: 'Sent program brochure with curriculum, schedule, and career outcomes.' },
      { type: 'MEETING', content: 'Campus tour and information session - Met with instructors.' },
      { type: 'NOTE', content: 'Student has basic HTML knowledge, wants career change to software development.' },
      { type: 'EMAIL', content: 'Sent enrollment application and financing options information.' },
      { type: 'CALL', content: 'Discussed ISA (Income Share Agreement) vs upfront tuition payment.' },
      { type: 'NOTE', content: 'Student prefers ISA - No upfront payment, 15% income for 2 years after placement.' },
      { type: 'EMAIL', content: 'Sent ISA agreement and enrollment paperwork for next cohort.' },
      { type: 'MEETING', content: 'Admissions interview - Assessed motivation and learning readiness.' },
      { type: 'CALL', content: 'Accepted into April cohort - Sent welcome packet and pre-work.' },
      { type: 'EMAIL', content: 'Sent pre-bootcamp prep materials - Basic JavaScript and Git tutorials.' },
      { type: 'NOTE', content: 'Student completed pre-work assignments - Ready for bootcamp start.' },
      { type: 'CALL', content: 'Orientation call - Reviewed schedule, expectations, and support resources.' },
      { type: 'EMAIL', content: 'Sent first day logistics, parking info, and what to bring.' },
      { type: 'NOTE', content: 'Enrolled and confirmed for April 1st start date - 16-week program.' },
    ],

    AUTOMOTIVE: [
      { type: 'CALL', content: 'Customer interested in luxury SUV - Budget around $60K.' },
      { type: 'EMAIL', content: 'Sent inventory photos of 3 BMW X5 models matching preferences.' },
      { type: 'MEETING', content: 'Showroom visit - Test drove 2023 BMW X5 and 2024 Mercedes GLE.' },
      { type: 'NOTE', content: 'Customer prefers BMW X5 M Sport package - Wants trade-in appraisal.' },
      { type: 'CALL', content: 'Trade-in vehicle inspection scheduled for tomorrow morning.' },
      { type: 'EMAIL', content: 'Trade-in offer: $18K for 2018 Honda CRV - Customer reviewing.' },
      { type: 'NOTE', content: 'Customer accepted trade value - Negotiating BMW X5 price.' },
      { type: 'MEETING', content: 'Price negotiation - Agreed on $58,500 for BMW X5 M Sport.' },
      { type: 'CALL', content: 'Discussed financing options - Customer pre-approved through own bank.' },
      { type: 'EMAIL', content: 'Sent purchase agreement and extended warranty options.' },
      { type: 'NOTE', content: 'Customer declined extended warranty - Wants delivery next week.' },
      { type: 'MEETING', content: 'Contract signing - Finalized paperwork and payment processing.' },
      { type: 'CALL', content: 'Vehicle detailing complete - Scheduled delivery for Thursday.' },
      { type: 'EMAIL', content: 'Sent delivery confirmation with vehicle tutorial appointment time.' },
      { type: 'NOTE', content: 'Vehicle delivered - Customer very satisfied, left 5-star review.' },
    ],
  };

  return sectorActivities[sector] || [];
}
